/*
  Project portfolio — photographs supplied by Victoria, one folder per project in
  src/assets/portfolio/<slug>/. Each photo exists as <name>-lg.webp (≤1800px) and
  <name>-sm.webp (800px); metadata is stripped so no location data is published.
  The first photo of each project is its cover. `story` is the full write-up shown
  on the project's own page; `summary` (its first paragraph) introduces it elsewhere.
*/

const files = import.meta.glob<string>("/src/assets/portfolio/**/*.webp", {
  eager: true,
  import: "default",
});

export type PortfolioPhoto = {
  name: string;
  lg: string;
  sm: string;
  w: number;
  h: number;
  title: string;
  caption: string;
};

export type PortfolioProject = {
  slug: string;
  title: string;
  location: string;
  /** Shown after the location, e.g. "Kinloch · Residential · Smart home". */
  tags: string[];
  /** Gallery filters for the project's photos, when they differ from `tags`. */
  galleryTags?: string[];
  summary: string;
  story?: string[];
  /** Heading for the details list, e.g. "Lighting & electrical details" */
  detailsTitle: string;
  details: string[];
  accolade?: string;
  photos: PortfolioPhoto[];
};

function photo(
  slug: string,
  name: string,
  w: number,
  h: number,
  title: string,
  caption: string,
): PortfolioPhoto {
  const base = `/src/assets/portfolio/${slug}/${name}`;
  const lg = files[`${base}-lg.webp`];
  const sm = files[`${base}-sm.webp`];
  if (!lg || !sm) throw new Error(`Portfolio image missing: ${base}-{lg,sm}.webp`);
  return { name, lg, sm, w, h, title, caption };
}

export const PORTFOLIO: PortfolioProject[] = [
  {
    slug: "cedar-gables",
    title: "Cedar Gables",
    location: "Kinloch",
    tags: ["Residential", "Balance showhome"],
    galleryTags: ["Residential", "New build"],
    summary:
      "Created as our own showhome, Cedar Gables gave us the opportunity to bring every layer of the home together — interiors, lighting, electrical, climate control and smart-home technology — as one considered design.",
    story: [
      "Created as our own showhome, Cedar Gables gave us the opportunity to bring every layer of the home together — interiors, lighting, electrical, climate control and smart-home technology — as one considered design.",
      "The interior palette was deliberately restrained, combining warm timber, soft neutral finishes, dark detailing and clean joinery to create a calm, contemporary home. Because the interiors and building services were developed together, lighting, air conditioning, power and technology could be integrated into the architecture rather than added as an afterthought.",
      "Lighting plays a major role throughout the home. Concealed LED is built into shelving, cabinetry, wardrobes, bedroom joinery and exterior seating, creating layers of warm light without relying on a ceiling full of fittings. Feature pendants and decorative wall lights introduce softer focal points, while task lighting is carefully placed through the kitchen, utility areas and living spaces.",
      "The kitchen became one of the key feature spaces. A sculptural linear pendant floats above the island, while integrated lighting highlights the rear joinery and open shelving. The lighting was designed to reinforce the material palette and create a completely different atmosphere in the evening.",
      "Air conditioning was treated with the same level of detail. Rather than allowing conventional grilles and equipment to interrupt the interiors, the system was coordinated into custom joinery and discreet linear grilles, allowing heating and cooling to remain visually integrated with the architecture.",
      "Smart-home control brings the electrical, lighting and climate systems together, allowing the home to respond simply to different times of day and ways of living. Lighting scenes, temperature and selected electrical functions can be controlled centrally while the technology itself remains largely hidden.",
      "The exterior continues the same approach. Concealed lighting beneath built-in deck seating, subtle deck-edge lighting and carefully positioned courtyard and soffit lighting connect the individual pavilion forms after dark and extend the living spaces into the landscape.",
      "Because this was our own showhome, it became an opportunity to demonstrate what is possible when interior design, lighting, electrical, air conditioning and automation are considered from the beginning as one complete system.",
    ],
    detailsTitle: "Design & services scope",
    details: [
      "Interior design and finish selection",
      "Complete electrical design and installation",
      "Architectural lighting design",
      "Smart-home integration and control",
      "Integrated air-conditioning system",
      "Custom linear grilles coordinated with interiors and joinery",
      "Concealed LED lighting to cabinetry and shelving",
      "Integrated wardrobe lighting",
      "Bedroom joinery and ambient lighting",
      "Kitchen task, feature and joinery lighting",
      "Feature pendants and decorative wall lighting",
      "Exterior deck, courtyard and soffit lighting",
      "Concealed LED beneath built-in outdoor seating",
      "Power and switching coordinated with furniture and joinery layouts",
    ],
    photos: [
      photo(
        "cedar-gables",
        "01-at-dusk",
        1800,
        1200,
        "At dusk",
        "Interior, soffit and deck-edge lighting connect the cedar pavilions as evening falls.",
      ),
      photo(
        "cedar-gables",
        "12",
        1800,
        1201,
        "Kitchen",
        "A sculptural linear pendant floats above the island, with concealed LED beneath the cabinetry and a linear air-conditioning grille set into the bulkhead.",
      ),
      photo(
        "cedar-gables",
        "17",
        1800,
        1189,
        "Island",
        "The pendant’s flowing line follows the island towards the lake-facing glazing.",
      ),
      photo(
        "cedar-gables",
        "13",
        1800,
        1201,
        "Scullery",
        "Lit open shelving and under-cabinet LED carry the kitchen lighting into the scullery, with the climate grille kept flush within the joinery.",
      ),
      photo(
        "cedar-gables",
        "14",
        1800,
        1201,
        "Lit shelving",
        "LED integrated beneath each timber shelf turns the coffee and bar station into a soft wall of light.",
      ),
      photo(
        "cedar-gables",
        "18",
        1800,
        1189,
        "Coffee nook",
        "Layered shelf lighting, a sculptural wall light and a discreet linear grille above the joinery — every service designed in.",
      ),
      photo(
        "cedar-gables",
        "16",
        1800,
        1201,
        "Open-plan living",
        "Lighting, climate and power are coordinated across the living, dining and kitchen as one continuous space.",
      ),
      photo(
        "cedar-gables",
        "15",
        1800,
        1201,
        "Living room",
        "A quiet layer of recessed light keeps the ceiling clean, leaving the view across the lake to lead.",
      ),
      photo(
        "cedar-gables",
        "06",
        1800,
        1201,
        "Lounge",
        "Twin glass pendants and concealed lighting along the curtain line soften the lounge behind the steel-framed screen.",
      ),
      photo(
        "cedar-gables",
        "10",
        1800,
        1201,
        "Bedroom",
        "Concealed LED along the bedhead ledge and a sculptural wall light create a warm, low-level glow.",
      ),
      photo(
        "cedar-gables",
        "11",
        1800,
        1201,
        "Guest bedroom",
        "Integrated ledge lighting and a single wall light keep the bedroom calm and uncluttered.",
      ),
      photo(
        "cedar-gables",
        "08",
        1800,
        1201,
        "Wardrobe",
        "Integrated LED runs along the hanging rails and shelving, lighting the walk-in wardrobe evenly.",
      ),
      photo(
        "cedar-gables",
        "07",
        1800,
        1201,
        "Bathroom",
        "Concealed LED beneath the floating timber vanity adds a soft night-time layer of light.",
      ),
      photo(
        "cedar-gables",
        "09",
        1800,
        1201,
        "Laundry",
        "Lit timber shelving carries the same joinery detailing into the laundry.",
      ),
      photo(
        "cedar-gables",
        "05",
        1800,
        1201,
        "Courtyard view",
        "The cedar-clad entry frames the courtyard and the lake beyond.",
      ),
      photo(
        "cedar-gables",
        "02-deck-at-sunset",
        1800,
        1201,
        "Deck at sunset",
        "Concealed LED beneath the built-in deck seating defines the edge of the outdoor living area.",
      ),
      photo(
        "cedar-gables",
        "03-pavilions-at-dusk",
        1800,
        1348,
        "Pavilions from above",
        "From the hillside, the pavilions read as a cluster of warm, lit forms against the landscape.",
      ),
      photo(
        "cedar-gables",
        "04-courtyard-at-dusk",
        1800,
        1200,
        "Courtyard at dusk",
        "Courtyard and soffit lighting link the pavilions and extend the living spaces outdoors.",
      ),
    ],
  },
  {
    slug: "courtyard-house",
    title: "Courtyard House",
    location: "Taupō district",
    tags: ["Residential", "New build"],
    accolade:
      "Gold Award — Master Builders House of the Year 2025, Bay of Plenty & Central Plateau",
    summary:
      "The electrical and lighting design for Courtyard House was developed to work seamlessly with the home’s timber interiors, strong architectural lines and expansive lake views. Rather than competing with the architecture, the lighting was carefully integrated to emphasise material, form and atmosphere throughout the home.",
    story: [
      "The electrical and lighting design for Courtyard House was developed to work seamlessly with the home’s timber interiors, strong architectural lines and expansive lake views. Rather than competing with the architecture, the lighting was carefully integrated to emphasise material, form and atmosphere throughout the home.",
      "In the kitchen and dining areas, slim linear pendants create a clean architectural line above the island and dining spaces, while recessed LED lighting follows the joinery to provide a softer layer of illumination and highlight the warmth and texture of the timber cabinetry. The concealed lighting was planned as part of the joinery itself, allowing the fittings and wiring to disappear into the architecture.",
      "In the living areas, feature pendants were selected to suit the scale and geometry of each space. A sculptural drum pendant sits beneath the timber-lined ceiling, drawing attention to the changing ceiling height and creating a warm focal point after dark. Carefully positioned recessed lighting provides the functional layer of light without interrupting the simplicity of the ceiling.",
      "The electrical layout was coordinated around the open-plan interior, cabinetry, glazing and furniture placement, ensuring switches, outlets and lighting controls were positioned where they were needed while remaining visually discreet. Particular attention was given to the transition between indoor and outdoor spaces, with electrical and lighting points planned to support the large opening doors, decks and entertaining areas.",
      "Outside, lighting continues through the courtyard, pergola and landscaped areas. Subtle architectural and garden lighting picks up the structure of the home and extends the interior atmosphere beyond the glass, creating depth around the building without overpowering the night environment.",
      "The result is a layered lighting scheme that moves from practical task lighting during the day to a softer, more atmospheric setting in the evening — highlighting the timber, joinery, architecture and views while keeping the electrical installation clean and understated.",
    ],
    detailsTitle: "Lighting & electrical details",
    details: [
      "Architectural linear pendants to the kitchen and dining areas",
      "Integrated LED lighting within and alongside custom joinery",
      "Feature pendant lighting to the lounge and living spaces",
      "Recessed lighting coordinated with timber ceilings and architectural lines",
      "Discreet switch and power-point placement throughout the interiors",
      "Electrical coordination around cabinetry, glazing and furniture layouts",
      "Courtyard, pergola and deck lighting",
      "Landscape and garden lighting to extend the home after dark",
      "Layered lighting designed for task, ambient and feature illumination",
    ],
    photos: [
      photo(
        "courtyard-house",
        "01-courtyard-at-dusk",
        1313,
        851,
        "Courtyard at dusk",
        "Integrated pergola, courtyard and landscape lighting extends the architecture into the evening.",
      ),
      photo(
        "courtyard-house",
        "04-kitchen-and-dining",
        1320,
        880,
        "Kitchen & dining",
        "Linear pendant lighting and integrated LED detailing reinforce the clean lines of the kitchen joinery.",
      ),
      photo(
        "courtyard-house",
        "02-living-room",
        1320,
        873,
        "Living room",
        "A sculptural pendant beneath the timber-lined ceiling creates a warm focal point while recessed lighting provides a quieter secondary layer.",
      ),
      photo(
        "courtyard-house",
        "03-kitchen",
        1320,
        878,
        "Kitchen",
        "Architectural task lighting over the island is balanced with concealed joinery lighting and the natural light from the lake-facing glazing.",
      ),
      photo(
        "courtyard-house",
        "06",
        1536,
        1024,
        "Kitchen joinery",
        "Concealed LED beneath the overhead cabinetry washes the benchtop, while a slim linear pendant traces the length of the island.",
      ),
      photo(
        "courtyard-house",
        "07",
        1536,
        1024,
        "Dining",
        "Recessed linear fittings sit flush within the ceiling above the dining table, leaving the lake-facing glazing uninterrupted.",
      ),
      photo(
        "courtyard-house",
        "05-lounge",
        1320,
        876,
        "Lounge",
        "A feature pendant, scaled to the raked timber ceiling, anchors the curved sofa and the quieter end of the living space.",
      ),
    ],
  },
  {
    slug: "fold-house",
    title: "Fold House",
    location: "Kinloch",
    tags: ["Residential", "New build"],
    summary:
      "The electrical and lighting design for Fold House was developed around the home’s distinctive geometry, using continuous lines of light to reinforce the curves, angles and changing ceiling forms throughout the building.",
    story: [
      "The electrical and lighting design for Fold House was developed around the home’s distinctive geometry, using continuous lines of light to reinforce the curves, angles and changing ceiling forms throughout the building.",
      "Rather than relying on a conventional grid of downlights, the lighting was integrated into the architecture itself. Recessed LED channels run through hallways, follow the stair profile and trace the curved exterior soffit, creating a consistent visual language from inside to out. The result is lighting that feels deliberate and architectural, while remaining clean and unobtrusive.",
      "In the open-plan living spaces, concealed linear lighting follows the sloping ceiling line, drawing the eye through the room and emphasising the height and form of the interior. Carefully positioned downlights provide practical task lighting where required without interrupting the simplicity of the ceiling.",
      "The kitchen and dining areas combine functional and feature lighting. A slim linear fitting provides focused illumination over the kitchen island, while the sculptural elliptical pendant over the dining table adds a softer focal point beneath the large circular ceiling feature. The two lighting styles work together to define each zone without breaking up the open-plan layout.",
      "One of the strongest details is the hallway, where a recessed LED channel runs continuously alongside the smoked-glass wall. The clean line of light guides movement through the home while reflecting subtly in the glazing, adding depth without the need for additional decorative fittings.",
      "At the stairwell, lighting becomes part of the structure. A continuous LED line follows the angle of the stair and balustrade, highlighting the floating timber treads and drawing attention to the geometry of the space. Suspended globe pendants provide a contrasting decorative layer and soften the strong linear elements.",
      "Outside, the same approach continues beneath the curved deck soffit. A concealed LED line follows the full sweep of the roofline, defining the curve after dark and providing warm, even illumination across the outdoor living area without introducing visible fittings. From a distance, the lighting becomes part of the silhouette of the building.",
      "The electrical installation was carefully coordinated with the ceiling forms, glazing, joinery and structural details so that cabling, drivers, switching and fittings could remain visually discreet. The finished result is a layered lighting scheme that provides practical illumination while allowing the architecture itself to remain the focus.",
    ],
    detailsTitle: "Lighting & electrical details",
    details: [
      "Continuous recessed LED lighting following the curved exterior soffit",
      "Concealed linear lighting integrated into sloping and raked ceilings",
      "Recessed LED channel running the length of the hallway",
      "Linear stair lighting following the profile of the balustrade and treads",
      "Sculptural pendant lighting through the stairwell",
      "Elliptical feature pendant above the dining area",
      "Linear task lighting above the kitchen island",
      "Carefully positioned recessed downlights for functional illumination",
      "Lighting coordinated with glazing, cabinetry and architectural ceiling lines",
      "Discreet integration of LED drivers, cabling and electrical components",
      "Layered interior and exterior lighting designed to work together after dark",
    ],
    photos: [
      photo(
        "fold-house",
        "02-aerial-at-sunset",
        1320,
        1315,
        "Aerial at sunset",
        "The home’s curved roof forms and stepped geometry establish the architectural language carried through the lighting design.",
      ),
      photo(
        "fold-house",
        "07",
        1536,
        1024,
        "Curved deck",
        "A concealed LED line traces the sweeping soffit, turning the roofline into a defining feature after dark.",
      ),
      photo(
        "fold-house",
        "03-kitchen-and-dining",
        1320,
        1317,
        "Kitchen & dining",
        "A sculptural elliptical pendant defines the dining zone, balanced by clean linear task lighting over the kitchen island.",
      ),
      photo(
        "fold-house",
        "04-open-plan-living",
        1800,
        1350,
        "Open-plan living",
        "Concealed lighting follows the sloping ceiling line, reinforcing the architecture while recessed downlights provide focused task illumination.",
      ),
      photo(
        "fold-house",
        "05-hallway",
        1350,
        1800,
        "Hallway",
        "A continuous recessed LED channel runs alongside the smoked-glass wall, creating a clean line of light through the interior.",
      ),
      photo(
        "fold-house",
        "06-stair",
        1800,
        1350,
        "Stair",
        "Integrated linear lighting follows the stair profile, highlighting the floating timber treads and strong geometry of the balustrade.",
      ),
      photo(
        "fold-house",
        "10",
        1024,
        1536,
        "Stairwell",
        "Suspended globe pendants soften the stairwell, while a continuous recessed line of light carries the geometry overhead.",
      ),
      photo(
        "fold-house",
        "09",
        1536,
        1024,
        "Dining nook",
        "The large circular ceiling feature crowns the banquette dining nook, with warm concealed LED tracing the top of the joinery.",
      ),
      photo(
        "fold-house",
        "08",
        1536,
        1024,
        "Deck at sunset",
        "The curved timber soffit frames the lake at sunset — by dusk, the concealed LED line takes over.",
      ),
    ],
  },
  {
    slug: "lake-house",
    title: "Lake House",
    location: "Taupō district",
    tags: ["Residential", "Lighting", "Electrical", "Air-Conditioning"],
    galleryTags: ["Residential"],
    summary:
      "The Lake House was approached as a fully coordinated lighting and electrical project, with the design developed around the home’s cedar ceilings, oak flooring, dark timber walls and expansive lake views.",
    story: [
      "The Lake House was approached as a fully coordinated lighting and electrical project, with the design developed around the home’s cedar ceilings, oak flooring, dark timber walls and expansive lake views.",
      "Balance completed the lighting design and electrical installation throughout the home, with particular attention given to integrating the lighting into the architecture rather than relying on conventional fittings alone.",
      "Concealed LED lighting plays a major role through the interior. Continuous cove lighting washes across the cedar-lined ceilings, bringing out the warmth and texture of the timber while keeping the light source itself largely hidden. In the gallery and circulation spaces, the lighting follows the architecture and creates a softer transition between the darker timber walls and lighter flooring.",
      "Small recessed and pinpoint downlights were carefully placed within the cedar soffits and ceilings, providing practical illumination without interrupting the clean lines overhead. In the kitchen, concealed LED beneath the island creates a low-level glow across the oak floor, adding depth to the space at night while allowing the joinery to remain visually light.",
      "Lighting continues through the exterior and landscaped areas, with low-level step lighting and garden spotlights providing subtle wayfinding and highlighting planting without overwhelming the setting.",
      "Heating and cooling were treated with the same attention to detail. Floor-mounted heat pumps were integrated into custom joinery units, allowing the equipment to sit quietly within the interior rather than becoming a visual feature. The joinery was coordinated around airflow and access requirements so the units could operate effectively while remaining discreet.",
      "The result is a home where the electrical, lighting and climate systems sit quietly behind the architecture — enhancing the timber, joinery and natural materials without competing with the lake outlook.",
    ],
    detailsTitle: "Lighting, electrical & climate scope",
    details: [
      "Complete residential electrical installation",
      "Full architectural lighting design",
      "Concealed LED cove lighting to cedar ceilings",
      "Continuous linear lighting through gallery spaces",
      "Low-level LED lighting beneath the kitchen island",
      "Pinpoint downlights integrated into timber soffits",
      "Recessed architectural lighting throughout the interiors",
      "Exterior step and pathway lighting",
      "Garden and landscape spot lighting",
      "Floor-mounted heat pumps",
      "Heat pumps integrated into custom joinery units",
      "Electrical coordination with cabinetry and interior finishes",
      "Power and switching coordinated with furniture and room layouts",
      "Final commissioning and fit-off",
    ],
    photos: [
      photo(
        "lake-house",
        "12",
        1800,
        1200,
        "Island to the lake",
        "Indirect light along the ceiling edges keeps the cedar glowing without a single visible fitting over the view.",
      ),
      photo(
        "lake-house",
        "21",
        1800,
        1200,
        "Kitchen & living",
        "Cove lighting runs beneath the raked cedar ceilings as the kitchen and living spaces open to the lake.",
      ),
      photo(
        "lake-house",
        "01-island",
        1800,
        1200,
        "Kitchen island",
        "Concealed LED lighting beneath the island creates a soft wash of light across the oak floor.",
      ),
      photo(
        "lake-house",
        "20",
        1800,
        1200,
        "Kitchen joinery",
        "Concealed LED beneath the overhead cabinetry and the island’s low-level glow layer the kitchen after dark.",
      ),
      photo(
        "lake-house",
        "02-cedar-ceiling",
        1800,
        1200,
        "Cedar ceiling",
        "Indirect LED lighting reveals the warmth and grain of the cedar while keeping the light source hidden.",
      ),
      photo(
        "lake-house",
        "19",
        1800,
        1200,
        "Kitchen & dining",
        "The island, dining and living zones share one continuous ceiling of warm, indirect light.",
      ),
      photo(
        "lake-house",
        "14",
        1200,
        1800,
        "Dining",
        "Indirect cove lighting follows the angled ceiling planes above the dining and living areas.",
      ),
      photo(
        "lake-house",
        "13",
        1800,
        1436,
        "Living to the lake",
        "The lighting is held back to the ceiling edges so the full-height glazing and lake view stay clear.",
      ),
      photo(
        "lake-house",
        "03-gallery",
        1200,
        1800,
        "Gallery",
        "A continuous cove of warm light runs the length of the gallery, emphasising the timber ceiling and architectural rhythm.",
      ),
      photo(
        "lake-house",
        "16",
        1200,
        1800,
        "Gallery corridor",
        "Warm cove light skims the cedar and the charred timber wall, drawing the eye along the corridor.",
      ),
      photo(
        "lake-house",
        "09",
        1169,
        1755,
        "Corridor",
        "Linear cove lighting carries the rhythm of the beams through the circulation spine.",
      ),
      photo(
        "lake-house",
        "08",
        1134,
        1710,
        "Ceiling detail",
        "Concealed LED reveals the grain of the cedar where it meets the charred timber wall.",
      ),
      photo(
        "lake-house",
        "04-hallway",
        1198,
        1800,
        "Hallway",
        "Pinpoint fittings sit discreetly within the cedar soffit, leading into the illuminated gallery.",
      ),
      photo(
        "lake-house",
        "17",
        1200,
        1800,
        "Entry",
        "A wall light marks the entry, with cove lighting glowing through to the gallery beyond.",
      ),
      photo(
        "lake-house",
        "15",
        1200,
        1800,
        "Shower",
        "A concealed LED cove washes down the tiled shower walls from above.",
      ),
      photo(
        "lake-house",
        "10",
        1124,
        1694,
        "Integrated climate",
        "Floor-mounted heat pumps were built into custom joinery, providing discreet heating and cooling without disrupting the interior.",
      ),
      photo(
        "lake-house",
        "11",
        1800,
        1384,
        "Step lighting",
        "LED recessed beneath the timber step nosings lights the outdoor stair without glare.",
      ),
      photo(
        "lake-house",
        "05-garden-light",
        1800,
        1200,
        "Garden lighting",
        "Low-level landscape lighting provides subtle wayfinding and highlights the planting after dark.",
      ),
      photo(
        "lake-house",
        "06",
        1139,
        756,
        "Outdoor room",
        "The covered outdoor room and courtyard, wired and lit for evening living by the lake.",
      ),
      photo(
        "lake-house",
        "07",
        1137,
        761,
        "Courtyard",
        "Cedar soffits and timber decking frame the courtyard between the living wings.",
      ),
    ],
  },
  {
    slug: "beechtree-studio",
    title: "Beechtree Studio",
    location: "Taupō district",
    tags: ["Commercial", "New build"],
    summary:
      "Beechtree Studio was a complete commercial electrical and lighting project, with Balance delivering the lighting design, electrical installation, heat pump systems and emergency lighting throughout the two-storey headquarters.",
    story: [
      "Beechtree Studio was a complete commercial electrical and lighting project, with Balance delivering the lighting design, electrical installation, heat pump systems and emergency lighting throughout the two-storey headquarters.",
      "The lighting design was developed to suit the different functions of the building, from client-facing offices and shared spaces through to the workshop and circulation areas. Architectural lighting was used where it could add character to the building, while practical workplace lighting was selected to provide consistent, functional illumination for day-to-day use.",
      "At the glazed frontage, soffit downlights and wall-mounted fittings create a warm, controlled exterior presence after dark and highlight the building’s timber and black detailing. Inside the offices, black track lighting follows the ceiling geometry, giving the spaces a clean architectural finish while allowing light to be directed where it is needed.",
      "The double-height stairwell became one of the main feature spaces. A cluster of suspended glass pendants drops through the void, while concealed LED lighting beneath the timber handrails provides a softer layer of illumination and improves visibility through the stair. The combination of feature and integrated lighting gives the space a strong identity without compromising functionality.",
      "The workshop required a very different approach. High-bay lighting provides broad, practical illumination across the larger working area, with the electrical layout designed around the operational requirements of the space. The installation included main distribution, switchboards, sub-mains, cable management and power infrastructure serving the offices, workshop and shared areas.",
      "Heat pump systems were installed to provide efficient heating and cooling across the occupied spaces, with equipment positioned and coordinated to sit cleanly within the architecture and interior layout.",
      "Emergency lighting was also incorporated throughout the building, providing compliant illumination to circulation areas and exit routes while remaining visually unobtrusive within the finished spaces.",
      "The result is a coordinated commercial installation where lighting, power, mechanical services and life-safety systems work together as one integrated package.",
    ],
    detailsTitle: "Electrical & lighting scope",
    details: [
      "Complete commercial electrical installation",
      "Full lighting design and lighting specification",
      "Main switchboard, distribution and labelled sub-mains",
      "Office power, data and general electrical services",
      "Architectural track lighting throughout office areas",
      "High-bay lighting to the workshop",
      "Exterior soffit lighting and façade wall lighting",
      "Feature pendant cluster through the double-height stairwell",
      "Concealed LED lighting beneath timber handrails",
      "Emergency and exit lighting throughout the building",
      "Heat pump supply and installation",
      "Electrical coordination for heating and cooling systems",
      "Cable management and distribution infrastructure",
      "Lighting and electrical commissioning",
    ],
    photos: [
      photo(
        "beechtree-studio",
        "01-front-at-dusk",
        1320,
        1324,
        "Front at dusk",
        "Architectural soffit and façade lighting create a strong, welcoming presence across the glazed two-storey frontage.",
      ),
      photo(
        "beechtree-studio",
        "02-entry-at-dusk",
        1041,
        1510,
        "Entry at dusk",
        "The glazed entry glows after dark, with the lit stair visible through the double-height façade.",
      ),
      photo(
        "beechtree-studio",
        "03-stairwell-pendants",
        1086,
        1448,
        "Stairwell",
        "A suspended glass pendant cluster and concealed handrail lighting bring both feature and functional illumination to the double-height stair.",
      ),
      photo(
        "beechtree-studio",
        "04-stair-from-above",
        1086,
        1448,
        "Stair from above",
        "Looking down through the void: the pendant cluster overhead and concealed LED beneath both handrails.",
      ),
      photo(
        "beechtree-studio",
        "05-lit-handrail",
        1041,
        1511,
        "Handrail lighting",
        "LED concealed beneath the timber handrail lights each tread evenly and without glare.",
      ),
      photo(
        "beechtree-studio",
        "06-office",
        1451,
        1084,
        "Office",
        "Black track lighting follows the ceiling geometry, providing flexible illumination across the office spaces.",
      ),
      photo(
        "beechtree-studio",
        "07-open-office",
        1448,
        1086,
        "Open-plan office",
        "Continuous track around the ceiling perimeter allows fittings to be re-aimed as the workspace changes.",
      ),
      photo(
        "beechtree-studio",
        "08-workshop",
        1086,
        1448,
        "Workshop",
        "High-bay lighting provides even, practical illumination across the workshop floor.",
      ),
      photo(
        "beechtree-studio",
        "09-switchboard",
        1086,
        1448,
        "Distribution",
        "Main electrical distribution and labelled sub-mains were installed to serve the offices, workshop and building services.",
      ),
      photo(
        "beechtree-studio",
        "10-sub-mains",
        1041,
        1511,
        "Sub-mains",
        "Each sub-main is labelled at the point of entry — offices, workshops and incoming supply identified for future servicing.",
      ),
      photo(
        "beechtree-studio",
        "11-on-site",
        1086,
        1448,
        "On site",
        "The Balance van on site at the completed headquarters.",
      ),
    ],
  },
  {
    slug: "black-gable-house",
    title: "Black Gable House",
    location: "Taupō district",
    tags: ["Residential", "New build"],
    summary:
      "Black Gable House was delivered as a fully coordinated lighting, electrical and ducted air-conditioning project, with each system designed to complement the home’s dark exterior, warm timber interiors and open-plan living spaces.",
    story: [
      "Black Gable House was delivered as a fully coordinated lighting, electrical and ducted air-conditioning project, with each system designed to complement the home’s dark exterior, warm timber interiors and open-plan living spaces.",
      "Balance completed the full electrical installation and lighting design, developing a layered scheme that gives the home a strong presence after dark while remaining clean and understated during the day.",
      "Externally, uplighting through the landscaping draws attention to the planting and vertical forms around the house, while soffit lighting runs beneath the eaves and across the garage to provide practical illumination and define the architecture. The contrast between the dark cladding and warm exterior lighting gives the home depth and character at night without over-lighting the site.",
      "Inside, the lighting was designed around the way each space is used. A slim linear pendant provides focused light over the kitchen island, while track lighting and recessed downlights create a flexible layer of illumination through the kitchen, dining and living areas. Decorative fittings are used selectively to add character without competing with the architecture.",
      "In the living room, recessed lighting is positioned around the timber-panelled fireplace wall, drawing attention to the materiality and creating a softer atmosphere in the evening. Bathrooms use discreet downlights and feature lighting to provide both functional task lighting and a more refined finish.",
      "The ducted air-conditioning system was integrated into the home to provide comfortable year-round heating and cooling while maintaining the simplicity of the interiors. Grilles and outlets were coordinated with the ceiling and room layouts so the system remains visually discreet.",
      "The electrical, lighting and climate systems were planned together from the outset, allowing power, switching, lighting and mechanical services to work as one coordinated installation.",
      "The result is a home that feels considered from every angle — with lighting that strengthens the architecture, climate control that disappears into the background, and a complete electrical installation supporting the way the home is lived in.",
    ],
    detailsTitle: "Lighting, electrical & climate scope",
    details: [
      "Complete residential electrical installation",
      "Full architectural lighting design",
      "Ducted air-conditioning system",
      "Integrated air-conditioning grilles",
      "Exterior soffit lighting",
      "Landscape and tree uplighting",
      "Garage and driveway lighting",
      "Linear pendant lighting over the kitchen island",
      "Track lighting through kitchen and open-plan areas",
      "Recessed downlighting throughout the home",
      "Feature lighting to dining and living spaces",
      "Bathroom and ensuite lighting",
      "Electrical coordination with cabinetry, ceilings and interior layouts",
      "Final electrical and air-conditioning commissioning",
    ],
    photos: [
      photo(
        "black-gable-house",
        "01-front-at-dusk",
        1448,
        1086,
        "Front at dusk",
        "Landscape uplighting and soffit lighting give the dark gabled forms depth and definition after sunset.",
      ),
      photo(
        "black-gable-house",
        "02-driveway-at-dusk",
        1448,
        1086,
        "Driveway at dusk",
        "Integrated soffit lighting washes the garage frontage while low-level garden lighting defines the approach.",
      ),
      photo(
        "black-gable-house",
        "03-garden-at-dusk",
        1448,
        1086,
        "Garden at dusk",
        "Carefully positioned uplights highlight the planting and extend the architecture into the landscape.",
      ),
      photo(
        "black-gable-house",
        "04-kitchen",
        1320,
        1043,
        "Kitchen",
        "A slim linear pendant defines the island, supported by recessed and track lighting through the surrounding space.",
      ),
      photo(
        "black-gable-house",
        "05-kitchen-and-dining",
        1320,
        867,
        "Kitchen & dining",
        "Linear and track lighting create a flexible layer of light across the open-plan kitchen and dining areas.",
      ),
      photo(
        "black-gable-house",
        "06-dining-and-living",
        1320,
        877,
        "Dining & living",
        "Decorative cylinder fittings and recessed downlights provide distinct layers of light across the open-plan interior.",
      ),
      photo(
        "black-gable-house",
        "07-living-room",
        1320,
        972,
        "Living room",
        "Recessed lighting is positioned around the timber fireplace wall to emphasise texture and create a softer evening atmosphere.",
      ),
      photo(
        "black-gable-house",
        "08-ensuite",
        1310,
        870,
        "Ensuite",
        "Task lighting and a feature pendant combine to provide practical illumination with a more refined finish.",
      ),
      photo(
        "black-gable-house",
        "09-bathroom",
        1320,
        873,
        "Bathroom",
        "Recessed lighting keeps the tiled shower and oak vanity bright, clean and uncluttered.",
      ),
    ],
  },
  {
    slug: "twin-pavilions",
    title: "Twin Pavilions",
    location: "Taupō district",
    tags: ["Residential", "Electrical", "Solar", "Air-Conditioning"],
    summary:
      "Twin Pavilions consists of two near-identical lakefront homes positioned side by side, with Balance delivering the complete electrical, ducted air-conditioning and solar installations across both residences.",
    story: [
      "Twin Pavilions consists of two near-identical lakefront homes positioned side by side, with Balance delivering the complete electrical, ducted air-conditioning and solar installations across both residences.",
      "Because the homes share the same architectural language and internal layout, the services were planned as a coordinated pair. Electrical distribution, lighting, power, heating and cooling, and solar generation were repeated consistently across both homes while being individually commissioned for each residence.",
      "The electrical installation was integrated throughout the open-plan living areas, kitchens, bedrooms and bathrooms, with power and lighting positioned to complement the clean interiors and expansive glazing toward the lake.",
      "Ducted air conditioning was installed throughout both homes to provide discreet year-round heating and cooling. Supply and return grilles were coordinated with the ceiling layouts so the systems remain unobtrusive within the finished interiors while delivering even airflow across the living and sleeping areas.",
      "Solar arrays were installed across multiple standing-seam roof planes, taking advantage of the available roof area while working with the architecture of each home. Mounting systems were carefully set out across the roof sections, with the electrical infrastructure for generation integrated back into each residence.",
      "Delivering the same systems across two adjoining homes required consistency in layout, installation and commissioning, while still allowing each property to operate entirely independently.",
      "The result is a pair of lakefront homes with electrical, climate and solar systems designed to sit quietly behind the architecture while providing efficient, reliable performance for everyday living.",
    ],
    detailsTitle: "Electrical, solar & climate scope",
    details: [
      "Complete electrical installation to both homes",
      "Independent electrical distribution for each residence",
      "General power and lighting throughout",
      "Electrical coordination with kitchens, bathrooms and joinery",
      "Ducted air-conditioning systems to both homes",
      "Integrated ceiling supply and return grilles",
      "Individual climate control for each residence",
      "Solar photovoltaic systems to both properties",
      "Solar arrays across multiple standing-seam roof sections",
      "Roof-mounted solar rail and panel installation",
      "Electrical integration of solar generation",
      "Final electrical, air-conditioning and solar commissioning",
    ],
    photos: [
      photo(
        "twin-pavilions",
        "01-array",
        1800,
        1350,
        "Solar array",
        "Photovoltaic panels were installed across multiple roof planes to maximise the available generation area.",
      ),
      photo(
        "twin-pavilions",
        "05-exterior",
        1274,
        1305,
        "Twin homes",
        "Two matching lakefront residences serviced with independent electrical, climate and solar systems.",
      ),
      photo(
        "twin-pavilions",
        "09",
        1536,
        1024,
        "Living & dining",
        "A slim linear pendant defines the dining table, with recessed lighting kept clear of the lake view.",
      ),
      photo(
        "twin-pavilions",
        "06-living-room",
        1305,
        1310,
        "Living room",
        "Electrical and ducted climate services were integrated discreetly into the open-plan lakefront interiors.",
      ),
      photo(
        "twin-pavilions",
        "07-living-and-dining",
        1320,
        1327,
        "Dining",
        "Pendants mark the dining table, with the lake framed by the stacker doors beyond.",
      ),
      photo(
        "twin-pavilions",
        "08-kitchen",
        1298,
        1316,
        "Kitchen",
        "Power, lighting and climate services were coordinated around the kitchen and surrounding open-plan spaces.",
      ),
      photo(
        "twin-pavilions",
        "10",
        1536,
        1024,
        "Ducted climate",
        "Discreet grilles distribute heating and cooling throughout each residence without dominating the interior.",
      ),
      photo(
        "twin-pavilions",
        "11",
        1536,
        1024,
        "Bathroom",
        "Concealed LED beneath the floating vanity and a globe wall light layer the bathroom with soft, low-glare light.",
      ),
      photo(
        "twin-pavilions",
        "02-rooftops",
        1800,
        1350,
        "Rooftops",
        "Solar arrays follow the standing-seam roof forms across both adjoining homes.",
      ),
      photo(
        "twin-pavilions",
        "04-rails-set-out",
        1012,
        1800,
        "Rails set out",
        "Mounting rails fixed precisely to the standing seams ahead of panel installation.",
      ),
    ],
  },
  {
    slug: "cedar-cube-house",
    title: "Cedar Cube House",
    location: "Taupō district",
    tags: ["Residential", "New build"],
    summary:
      "Cedar Cube House was delivered as a fully coordinated lighting, electrical and ducted air-conditioning project, with each system designed to sit cleanly within the architecture of the home.",
    story: [
      "Cedar Cube House was delivered as a fully coordinated lighting, electrical and ducted air-conditioning project, with each system designed to sit cleanly within the architecture of the home.",
      "Balance completed the full electrical installation and lighting design, developing a layered scheme that works with the home’s pale brick, dark cladding, warm timber and large areas of glazing.",
      "Externally, up-and-down wall lights graze the brickwork and emphasise the height and texture of the façade after dark. Around the deck, pool and landscaped areas, lighting was positioned to provide practical illumination while maintaining a warm, understated atmosphere. As evening falls, the interior lighting becomes part of the exterior composition, glowing through the full-height glazing and connecting the living spaces with the pool and outdoor areas.",
      "Inside, the kitchen lighting combines functional and architectural elements. A slim linear pendant provides focused light over the island, while concealed LED beneath the overhead cabinetry creates an even wash across the work surfaces and highlights the joinery. Recessed lighting throughout the open-plan spaces provides the general layer of illumination without competing with the clean interior lines.",
      "The ducted air-conditioning system was integrated into the home to provide discreet year-round heating and cooling. Linear grilles were coordinated with the ceilings and joinery so the system remains visually understated while maintaining comfortable airflow throughout the main living and bedroom areas.",
      "The electrical installation was planned alongside the lighting and air-conditioning systems from the beginning, allowing power, switching, mechanical services and lighting to be coordinated as one complete package.",
      "The result is a home where lighting, electrical and climate control work quietly together — enhancing the architecture by night while keeping the interiors clean and uncluttered.",
    ],
    detailsTitle: "Lighting, electrical & climate scope",
    details: [
      "Complete residential electrical installation",
      "Full architectural lighting design",
      "Ducted air-conditioning system",
      "Integrated air-conditioning grilles",
      "Exterior up-and-down wall lighting",
      "Architectural façade lighting",
      "Pool, deck and landscape lighting",
      "Linear pendant lighting above the kitchen island",
      "Concealed LED lighting beneath kitchen cabinetry",
      "Recessed lighting throughout the living areas",
      "Electrical coordination with cabinetry and interior layouts",
      "Power, switching and mechanical-service integration",
      "Final electrical and air-conditioning commissioning",
    ],
    photos: [
      photo(
        "cedar-cube-house",
        "03",
        1533,
        1026,
        "House at dusk",
        "Architectural lighting defines the brick and timber forms while the interiors glow through the full-height glazing.",
      ),
      photo(
        "cedar-cube-house",
        "04",
        1537,
        1023,
        "Wall lights at dusk",
        "Up-and-down fittings graze the pale brickwork, emphasising its texture and creating depth across the façade.",
      ),
      photo(
        "cedar-cube-house",
        "02",
        1545,
        1018,
        "Pool & living at sunset",
        "Interior, deck and pool lighting work together to extend the living spaces outdoors after dark.",
      ),
      photo(
        "cedar-cube-house",
        "01",
        1448,
        1086,
        "Kitchen",
        "A slim linear pendant defines the island, with concealed LED providing even task lighting across the rear joinery.",
      ),
      photo(
        "cedar-cube-house",
        "05-integrated-climate",
        960,
        700,
        "Integrated climate",
        "Ducted air conditioning is distributed through discreet linear grilles coordinated with the ceiling and interior detailing.",
      ),
    ],
  },
  {
    slug: "black-ridge-house",
    title: "Black Ridge House",
    location: "Kinloch",
    tags: ["Residential", "Smart home"],
    galleryTags: ["Residential", "New build", "Smart home"],
    summary:
      "Black Ridge House combines a strong material palette of dark exterior cladding and warm timber interiors with an electrical and climate-control installation designed to remain deliberately understated.",
    story: [
      "Black Ridge House combines a strong material palette of dark exterior cladding and warm timber interiors with an electrical and climate-control installation designed to remain deliberately understated.",
      "Balance completed the electrical installation throughout the home, together with the smart-home system and a zoned approach to heating and cooling. The upper level is serviced by ducted air conditioning, allowing conditioned air to be distributed discreetly through the bedrooms and living areas without introducing visually dominant equipment. Downstairs, a high-wall heat pump provides efficient heating and cooling while responding to the different requirements of the lower level.",
      "The electrical installation was coordinated closely with the timber-lined ceilings, custom joinery and large areas of glazing. Recessed downlights were carefully positioned within the timber ceilings to maintain clean architectural lines, while concealed LED lighting was incorporated around the kitchen joinery to provide a softer ambient layer after dark.",
      "The smart-home system brings lighting, climate and selected electrical functions together into a single, intuitive control platform. This allows the home to move easily between everyday, entertaining and evening settings while keeping conventional switches and controls visually restrained.",
      "At the entrance, recessed soffit lighting leads along the sheltered walkway and highlights the dark timber exterior without overpowering it. Inside, lighting remains warm and subtle, working with the natural timber surfaces rather than competing with them.",
      "The result is a home where electrical, automation and climate systems are largely unseen — quietly supporting the architecture, comfort and day-to-day use of the house.",
    ],
    detailsTitle: "Electrical, climate & smart-home scope",
    details: [
      "Complete residential electrical installation",
      "Smart-home integration",
      "Centralised lighting and climate control",
      "Ducted air conditioning to the upper level",
      "High-wall heat pump to the lower level",
      "Electrical integration of heating and cooling systems",
      "Recessed lighting through timber-lined ceilings",
      "Concealed LED lighting to kitchen joinery",
      "Architectural soffit lighting to the covered entrance",
      "Power and switching coordinated with joinery and interior layouts",
      "Exterior and circulation lighting",
    ],
    photos: [
      photo(
        "black-ridge-house",
        "01-exterior",
        1320,
        1175,
        "Exterior",
        "Dark timber cladding set into the native tussock, with the electrical services kept deliberately out of sight.",
      ),
      photo(
        "black-ridge-house",
        "02-entry",
        1320,
        887,
        "Entry",
        "Recessed soffit lighting guides the covered approach and highlights the dark timber exterior after dusk.",
      ),
      photo(
        "black-ridge-house",
        "03-kitchen",
        1320,
        889,
        "Kitchen",
        "Recessed downlights sit cleanly within the timber ceiling, with concealed LED adding a softer layer above the joinery.",
      ),
      photo(
        "black-ridge-house",
        "04-kitchen-to-living",
        1320,
        896,
        "Kitchen to living",
        "Lighting was coordinated with the continuous timber ceiling to maintain the strong architectural lines of the interior.",
      ),
    ],
  },
  {
    slug: "pool-courtyard",
    title: "Pool Courtyard",
    location: "Taupō",
    tags: ["Residential", "New build"],
    summary:
      "Pool Courtyard was delivered as a fully coordinated lighting, electrical and ducted air-conditioning project, with the services planned to sit quietly within the clean, contemporary architecture of the home.",
    story: [
      "Pool Courtyard was delivered as a fully coordinated lighting, electrical and ducted air-conditioning project, with the services planned to sit quietly within the clean, contemporary architecture of the home.",
      "Balance completed the full electrical installation and developed the lighting design throughout, creating a layered scheme that moves from strong architectural lighting at the entrance to softer integrated lighting within the interior.",
      "At the front of the home, concealed linear lighting above the garage, up-and-down wall fittings and low-level lights set into the stepping-stone path create a clear, welcoming approach after dark. The lighting was positioned to emphasise the simple form of the façade without over-lighting it.",
      "Inside, recessed lighting provides the general layer of illumination, while decorative fittings introduce character to key spaces. A feature pendant marks the high entry volume, with more subtle lighting used through the bedrooms and circulation areas.",
      "The bathrooms were treated with particular attention to detail. Concealed LED lighting within the shower niche creates a soft, integrated glow, while a continuous ceiling-edge LED adds another architectural layer to the ensuite without relying solely on downlights.",
      "The ducted air-conditioning system was integrated throughout the home to provide discreet year-round heating and cooling. Grilles and outlets were coordinated with the ceilings and room layouts so the system remains visually understated and does not interrupt the simplicity of the interiors.",
      "The electrical installation was coordinated alongside the lighting and air-conditioning from the beginning, allowing power, lighting, controls and mechanical services to work together as one complete package.",
      "The result is a clean, highly considered home where the electrical and climate systems remain largely in the background, while the lighting adds depth, warmth and definition to the architecture.",
    ],
    detailsTitle: "Lighting, electrical & climate scope",
    details: [
      "Complete residential electrical installation",
      "Full architectural lighting design",
      "Ducted air-conditioning system",
      "Integrated air-conditioning grilles",
      "Exterior architectural lighting",
      "Concealed LED above the garage door",
      "Up-and-down façade lighting",
      "Low-level lighting integrated into the entrance pavers",
      "Feature pendant lighting to the entry",
      "Recessed lighting throughout the home",
      "Concealed LED lighting within shower niches",
      "Architectural LED lighting to bathroom ceiling details",
      "Electrical services to outdoor and pool areas",
      "Power and switching coordinated with the interior layouts",
      "Final electrical and air-conditioning commissioning",
    ],
    photos: [
      photo(
        "pool-courtyard",
        "01",
        1672,
        941,
        "Front at dusk",
        "Linear, wall and low-level lighting combine to define the entrance and façade after dark.",
      ),
      photo(
        "pool-courtyard",
        "02-front-by-day",
        720,
        479,
        "Entry path",
        "Integrated lighting within the stepping-stone pavers creates a subtle illuminated approach to the home.",
      ),
      photo(
        "pool-courtyard",
        "03-lap-pool",
        720,
        479,
        "Pool",
        "Electrical services were coordinated for the pool and surrounding outdoor areas as part of the complete installation.",
      ),
      photo(
        "pool-courtyard",
        "04-entry-and-hall",
        720,
        524,
        "Entry & hall",
        "A sculptural pendant marks the high entry volume, with recessed lighting continuing through the hallway.",
      ),
      photo(
        "pool-courtyard",
        "05-bedroom",
        720,
        479,
        "Bedroom",
        "Recessed downlights keep the bedroom ceiling clean, continuing through to the ensuite and wardrobe.",
      ),
      photo(
        "pool-courtyard",
        "06-shower-niche",
        720,
        479,
        "Shower niche",
        "Concealed LED lighting is integrated into the tiled niche for a clean, soft layer of illumination.",
      ),
      photo(
        "pool-courtyard",
        "07-ensuite",
        720,
        479,
        "Ensuite",
        "A continuous ceiling-edge LED works with the illuminated shower niche to create a more architectural bathroom lighting scheme.",
      ),
    ],
  },
  {
    slug: "walnut-house",
    title: "Walnut House",
    location: "Taupō district",
    tags: ["Residential", "Lighting", "Electrical", "Air-Conditioning"],
    summary:
      "Walnut House was delivered as a fully integrated lighting, electrical and ducted air-conditioning project, with the building services carefully coordinated into the home’s extensive custom joinery.",
    story: [
      "Walnut House was delivered as a fully integrated lighting, electrical and ducted air-conditioning project, with the building services carefully coordinated into the home’s extensive custom joinery.",
      "Balance completed the full electrical installation and lighting design, while the ducted air-conditioning system was incorporated directly into the cabinetry and joinery rather than treated as a separate visible service.",
      "The dark timber joinery became a defining architectural element throughout the home, so the lighting was designed to work within it. Concealed LED lighting was integrated beneath shelves and along cabinetry to provide soft task and ambient light, bringing out the texture and warmth of the timber while keeping the fittings themselves hidden.",
      "In the kitchen and gallery areas, the joinery carries both the lighting and the climate-control systems. Linear air-conditioning grilles were built directly into the cabinetry, allowing conditioned air to be distributed discreetly without interrupting the clean ceiling planes or interior detailing.",
      "The same approach continues through the hallway and bedrooms, where concealed lighting is incorporated into shelving and bedhead joinery to create a warmer, lower-level layer of light in the evening.",
      "The electrical installation was coordinated closely with the cabinetry, lighting, appliances and air-conditioning system from the beginning, ensuring power, controls, cabling, grilles and lighting could all be resolved as part of the interior rather than added afterwards.",
      "The result is a highly integrated home where lighting, electrical and climate systems are almost absorbed into the joinery — providing comfort and functionality while allowing the architecture and materials to remain the focus.",
    ],
    detailsTitle: "Lighting, electrical & climate scope",
    details: [
      "Complete residential electrical installation",
      "Full architectural lighting design",
      "Fully ducted air-conditioning system",
      "Air-conditioning grilles integrated into custom joinery",
      "Air-Conditioning services coordinated with cabinetry and interior detailing",
      "Concealed LED lighting beneath shelving",
      "Integrated task lighting to kitchen and utility joinery",
      "LED lighting along hallway cabinetry",
      "Concealed bedroom and bedhead lighting",
      "Feature pendant lighting to the kitchen island",
      "Recessed downlighting through circulation spaces",
      "Power and switching coordinated with custom cabinetry",
      "Electrical and mechanical commissioning",
    ],
    photos: [
      photo(
        "walnut-house",
        "01-kitchen",
        1086,
        1448,
        "Kitchen",
        "Ducted air-conditioning grilles are fully integrated into the custom joinery, keeping the ceiling and interior lines clean.",
      ),
      photo(
        "walnut-house",
        "02-galley",
        1086,
        1448,
        "Galley",
        "Concealed LED lighting beneath the shelf illuminates the stone splashback while the climate system is built into the joinery above.",
      ),
      photo(
        "walnut-house",
        "03-hall",
        1086,
        1448,
        "Hall",
        "Integrated lighting runs through the cabinetry, creating a continuous layer of warm light along the circulation space.",
      ),
      photo(
        "walnut-house",
        "04-bedroom",
        1448,
        1086,
        "Bedroom",
        "Concealed LED lighting along the bedhead provides a softer evening setting without relying on overhead fittings.",
      ),
    ],
  },
  {
    slug: "the-arches",
    title: "The Arches",
    location: "Taupō",
    tags: ["Residential", "Renovation"],
    summary:
      "The Arches was a complete residential renovation, with Balance delivering the lighting design, electrical works and high-wall heat-pump systems as part of the transformation of the existing home.",
    story: [
      "The Arches was a complete residential renovation, with Balance delivering the lighting design, electrical works and high-wall heat-pump systems as part of the transformation of the existing home.",
      "The lighting design was developed around the new interior detailing, using a combination of concealed LED, track lighting, feature fittings and exterior lighting to give each renovated space its own character.",
      "In the lounge, the illuminated arched niches became a defining feature of the interior. Concealed LED lighting was integrated into the shelving to softly wash the curved forms and display areas, creating depth around the fireplace and television wall without relying on strong overhead light.",
      "The kitchen continues the more playful architectural language of the renovation. Adjustable track lighting provides focused illumination across the curved cabinetry and work surfaces, while the electrical layout was coordinated around the new joinery, appliances and updated room configuration.",
      "High-wall heat pumps were installed to provide efficient heating and cooling throughout the renovated living spaces. Their positions were carefully considered around windows, cabinetry and furniture to provide effective airflow while remaining as unobtrusive as possible within the finished rooms.",
      "Outside, the electrical and lighting work extends through the courtyard and covered deck. Wall-mounted fittings provide a warm layer of general illumination, while low-level step lights are integrated into the deck and pathways to improve visibility and guide movement through the outdoor spaces after dark.",
      "The electrical installation was updated alongside the renovation, allowing lighting, power, appliances and climate control to be coordinated with the new interiors rather than simply adapted around the existing layout.",
      "The finished project shows how considered electrical and lighting design can completely change the atmosphere of an existing home — adding warmth, functionality and character while supporting the new interior architecture.",
    ],
    detailsTitle: "Renovation, lighting & climate scope",
    details: [
      "Electrical works throughout the full renovation",
      "Complete lighting design",
      "Electrical coordination with new kitchen and interior joinery",
      "Concealed LED lighting to arched display niches",
      "Integrated shelving and feature lighting",
      "Adjustable track lighting to the kitchen",
      "Recessed and architectural lighting throughout renovated spaces",
      "High-wall heat-pump installation",
      "Power and electrical services for new appliances and layouts",
      "Exterior courtyard lighting",
      "Wall lighting beneath the covered deck",
      "Low-level deck and step lighting",
      "Final electrical and heat-pump commissioning",
    ],
    photos: [
      photo(
        "the-arches",
        "01-lounge",
        1320,
        881,
        "Lounge",
        "Concealed LED lighting traces the arched display niches, creating a warm architectural feature around the fireplace and television wall.",
      ),
      photo(
        "the-arches",
        "02-kitchen",
        1320,
        892,
        "Kitchen",
        "Adjustable track lighting provides focused illumination across the renovated kitchen, with electrical services coordinated around the new joinery.",
      ),
      photo(
        "the-arches",
        "03-courtyard-at-dusk",
        1320,
        888,
        "Courtyard at dusk",
        "Wall and low-level lighting create a warm, practical route through the redesigned courtyard.",
      ),
      photo(
        "the-arches",
        "04-covered-deck",
        1320,
        899,
        "Covered deck",
        "Wall-mounted fittings and integrated step lighting extend the renovated living spaces outdoors after dark.",
      ),
    ],
  },
  {
    slug: "hillside-house",
    title: "Hillside House",
    location: "Kinloch",
    tags: ["Residential", "New build"],
    summary:
      "Balance completed the full electrical installation for this new Kinloch home, taking the project from framing through to final fit-off.",
    story: [
      "Balance completed the full electrical installation for this new Kinloch home, taking the project from framing through to final fit-off.",
      "The electrical work was coordinated around the architecture, cedar cladding, large areas of glazing and outdoor living spaces, with particular attention given to creating a clean, unobtrusive finish throughout the home.",
      "Exterior lighting was integrated around the soffits, entry and deck areas to provide practical illumination while complementing the materials and form of the building. Recessed downlights sit neatly beneath the roof overhangs, while wall-mounted fittings frame key openings and add warmth to the exterior after dark.",
      "Low-level lighting was incorporated around the deck and landscaping to improve visibility and guide movement through the outdoor areas without overpowering the architecture. At the entry, a combination of soffit lighting, wall lighting and low-level fittings creates a clear and welcoming approach to the home.",
      "Internally, the electrical installation was planned and wired during the framing stage, allowing power, lighting and switching to be positioned cleanly around the final layouts and finishes.",
      "The result is a complete residential electrical installation that supports the home quietly and reliably, with careful attention to detail from first fix through to final commissioning.",
    ],
    detailsTitle: "Electrical scope",
    details: [
      "Complete residential electrical installation",
      "First-fix wiring from framing stage",
      "Final fit-off and commissioning",
      "Interior power and lighting circuits",
      "Exterior soffit lighting",
      "Wall lighting around entry and glazing",
      "Deck and low-level step lighting",
      "Exterior power requirements",
      "Switchboard and circuit distribution",
      "Power and switching coordinated with the finished layout",
    ],
    photos: [
      photo(
        "hillside-house",
        "01-exterior-at-dusk",
        1800,
        1200,
        "Exterior at dusk",
        "Recessed soffit lighting provides even illumination across the cedar-clad exterior.",
      ),
      photo(
        "hillside-house",
        "02-deck-at-dusk",
        1800,
        1359,
        "Deck at dusk",
        "Wall-mounted fittings and low-level deck lighting create a warm, practical layer of exterior light.",
      ),
      photo(
        "hillside-house",
        "03-entry-at-dusk",
        1200,
        1800,
        "Entry at dusk",
        "Soffit, wall and low-level lighting work together to define the entrance and approach after dark.",
      ),
      photo(
        "hillside-house",
        "04-front-door",
        1200,
        1800,
        "Front door",
        "Soffit downlights wash the entry, picking out the copper-toned door and timber step.",
      ),
      photo(
        "hillside-house",
        "05-step-light",
        1200,
        1800,
        "Step light",
        "Low-level lighting provides discreet illumination through the landscaped edge of the deck.",
      ),
      photo(
        "hillside-house",
        "06-entry-by-day",
        1800,
        1200,
        "Entry by day",
        "By day the cedar, concrete and glazing take the lead, with every fitting kept discreet.",
      ),
      photo(
        "hillside-house",
        "07-during-the-build",
        1200,
        1800,
        "Framing stage",
        "The home at framing stage — first-fix wiring planned around the final layout before the linings went on.",
      ),
    ],
  },
  {
    slug: "behind-the-walls",
    title: "Behind the Walls",
    location: "Taupō district",
    tags: ["New build", "Electrical workmanship"],
    galleryTags: ["New build", "First fix"],
    summary:
      "The quality of an electrical installation is often most visible before the walls and ceilings are closed in.",
    story: [
      "The quality of an electrical installation is often most visible before the walls and ceilings are closed in.",
      "At Balance, we put the same level of care into the work that will never be seen as we do into the finished fittings. Cable routes are planned before installation, runs are kept clean and organised, drops are grouped logically, and services are coordinated with the structure and other trades from the outset.",
      "Good pre-wiring is about more than appearance. Careful routing and clear organisation make the installation easier to complete, easier to identify and easier to service in the future. It also reduces unnecessary congestion behind linings and allows the final electrical fit-off to be completed cleanly and accurately.",
      "From switchboards and sub-mains through to lighting, power, data, automation and mechanical services, we approach the rough-in as the foundation of the finished electrical system.",
      "For us, workmanship doesn’t start when the lights go on. It starts with what goes behind the walls.",
    ],
    detailsTitle: "Our approach",
    details: [
      "Cable routes planned before installation",
      "Neat, consistent runs through framing and ceiling spaces",
      "Cable groups organised by circuit and destination",
      "Clean and considered drops to outlets and fittings",
      "Coordination around structural elements and other services",
      "Allowance for future access and maintenance",
      "Attention to detail from first fix through to final fit-off",
      "The same standard of workmanship in concealed areas as finished spaces",
    ],
    photos: [
      photo(
        "behind-the-walls",
        "01-ceiling-runs",
        1440,
        961,
        "Ceiling runs",
        "Carefully planned cable routes keep the installation organised and accessible before the ceiling is closed.",
      ),
      photo(
        "behind-the-walls",
        "02-first-fix",
        1350,
        1800,
        "First fix",
        "Electrical services are coordinated through the framing from the earliest stage of the build.",
      ),
      photo(
        "behind-the-walls",
        "03-cable-drops",
        1350,
        1800,
        "Cable drops",
        "Grouped and organised cable drops create a cleaner installation and simplify the final fit-off.",
      ),
      photo(
        "behind-the-walls",
        "04-arched-opening",
        1350,
        1800,
        "Routing detail",
        "Consistent cable routing and fixing reflect the standard of workmanship carried through the entire project.",
      ),
    ],
  },
];

/** Look up one portfolio photo by file name, e.g. getPhoto("courtyard-house", "02-living-room"). */
export function getPhoto(slug: string, name: string): PortfolioPhoto & { project: string } {
  const project = PORTFOLIO.find((p) => p.slug === slug);
  const found = project?.photos.find((ph) => ph.name === name);
  if (!project || !found) throw new Error(`No portfolio photo ${slug}/${name}`);
  return { ...found, project: project.title };
}

export function getProject(slug: string): PortfolioProject | undefined {
  return PORTFOLIO.find((p) => p.slug === slug);
}

/*
  Gallery filters use a project's tags (or galleryTags), except where one photo shows
  a different kind of work from the rest of its project (e.g. the solar array vs the house).
*/
const PHOTO_TAGS: Record<string, string[]> = {
  "twin-pavilions/01-array": ["Solar"],
  "twin-pavilions/02-rooftops": ["Solar"],
  "twin-pavilions/04-rails-set-out": ["Solar"],
  "pool-courtyard/01": ["Residential"],
  "pool-courtyard/02-front-by-day": ["Residential"],
  "pool-courtyard/03-lap-pool": ["Pool"],
  "pool-courtyard/04-entry-and-hall": ["Residential", "Air-Conditioning"],
  "pool-courtyard/05-bedroom": ["Residential", "Air-Conditioning"],
  "pool-courtyard/06-shower-niche": ["Residential"],
  "pool-courtyard/07-ensuite": ["Residential"],
  "the-arches/02-kitchen": ["Residential", "Renovation", "Air-Conditioning"],
  "hillside-house/07-during-the-build": ["New build", "First fix"],
  "lake-house/10": ["Residential", "Air-Conditioning"],
  "cedar-cube-house/01": ["Residential", "New build", "Air-Conditioning"],
  "cedar-cube-house/05-integrated-climate": ["Residential", "New build", "Air-Conditioning"],
  "cedar-cube-house/02": ["Residential", "New build", "Pool"],
  "cedar-gables/12": ["Residential", "New build", "Air-Conditioning"],
  "cedar-gables/13": ["Residential", "New build", "Air-Conditioning"],
  "cedar-gables/18": ["Residential", "New build", "Air-Conditioning"],
  "walnut-house/04-bedroom": ["Residential", "Air-Conditioning"],
};

export function photoTags(project: PortfolioProject, photo: PortfolioPhoto): string[] {
  return PHOTO_TAGS[`${project.slug}/${photo.name}`] ?? project.galleryTags ?? project.tags;
}

export const PORTFOLIO_PHOTO_COUNT = PORTFOLIO.reduce((n, p) => n + p.photos.length, 0);
