/*
  Balance Electrical's Terms of Trade, shown at /terms-of-trade. Quotes, booking messages,
  invoices and payment reminders cite these clauses by number, and the page numbers them from
  their position (section 14, clause 4 is "14.4", at #overdue-4). Adding, removing or moving a
  clause renumbers everything after it, so change the version and date, and update the Katipolt
  and Xero templates and reminder wording that cite clause numbers.
*/

export type TermsSection = { id: string; heading: string; clauses: string[] };

export const TERMS: {
  version: string;
  effective: string;
  effectiveIso: string;
  intro: string[];
  sections: TermsSection[];
} = {
  version: "1.0",
  effective: "6 October 2026",
  effectiveIso: "2026-10-06",
  intro: [
    "These Terms of Trade explain how Balance Electrical quotes for, carries out and invoices electrical work, and what happens if an invoice isn't paid. They apply to every quote, booking and invoice we issue, and become part of our agreement with you when you accept a quote or ask us to go ahead with work.",
    "They're written in plain English. Every section and clause is numbered, so either of us can point to the exact part that applies. For example, “Paying us” sets out when invoices are due.",
    "If you're a homeowner or otherwise a consumer, your rights under the Consumer Guarantees Act 1993, the Fair Trading Act 1986 and the Building Act 2004 always apply, and nothing in these terms takes them away. A few clauses apply only to business customers, such as builders, developers and commercial clients, and those clauses say so.",
    "In short: check your quote, confirm any changes in writing, pay by the due date on your invoice, and talk to us early if something's wrong or paying on time will be hard. We issue your electrical certificates as the law requires, whether or not an invoice has been paid.",
  ],
  sections: [
    {
      id: "about",
      heading: "About these terms",
      clauses: [
        "These Terms of Trade apply to all quotes, work, goods and services supplied by Balance Electrical Limited (NZBN 9429050562695), an electrical contracting company based in Taupō, New Zealand, trading as Balance Electrical. In these terms, “Balance Electrical”, “we”, “us” and “our” mean Balance Electrical Limited, and “you” means the customer named on the quote, booking, job or invoice.",
        "These terms apply only to Balance Electrical Limited. They don't apply to work you arrange directly with any other business, including Balance Air Conditioning, which is a separate company.",
        "You're a “consumer” if you get our goods or services for personal, domestic or household use, for example work on your own home. You're a “business customer” if you get them for the purposes of a business (in trade), for example as a builder, developer, commercial business, or a landlord or property manager acting for a rental business. Some clauses apply only to business customers, and they say so. Even if you're a business customer, the Consumer Guarantees Act 1993 may still apply to household-type goods and services you get from us, unless you have agreed to contract out of it as explained in “Guarantees and our responsibility”. If you're not sure which you are, ask us. If it's unclear, we'll treat you as a consumer.",
        "If you're a consumer, nothing in these terms limits or excludes your rights under the Consumer Guarantees Act 1993, the Fair Trading Act 1986, the Building Act 2004 or any other law that can't be excluded. Any clause that would do that doesn't apply to you.",
        "As the law requires, prescribed electrical work is carried out or supervised by electrical workers who are registered and licensed with the Electrical Workers Registration Board.",
        "You can contact us on 027 916 2077 or at enquiries@balanceelectrical.co.nz. Our hours are Monday to Friday, 7:30am to 5:30pm.",
        "This is version 1.0 of our Terms of Trade. It applies from 6 October 2026 to quotes we issue and work we book from that date, and replaces our earlier terms of trade for that work. Jobs you accepted before then are covered by the terms that applied when you accepted them.",
      ],
    },
    {
      id: "agreement",
      heading: "How our agreement is made",
      clauses: [
        "Our agreement with you is made up of your quote or booking, these Terms of Trade, and any variations we confirm in writing. If they conflict, the details written for your job in the quote or a written variation (such as the scope, price, stages, deposit and due date) take priority over these terms, but standard printed wording on a quote, invoice or other document does not. Any separate written contract we sign with you takes priority over all of them.",
        "You accept a quote, and these terms, when you do any of the following: sign the quote; reply by email or text message saying you accept it; accept it using the online acceptance link on the quote; or tell us to start, or let us start, the work after receiving the quote.",
        "For work we do without a written quote, such as call-outs, fault finding, repairs, maintenance and small jobs, we send you a link to these terms by email or text message when you book, or show them to you before we start. If you ask us to go ahead after that, you accept these terms for that work.",
        "Each quote and job has a quote or job number. Please use it whenever you contact us about the work or make a payment.",
        "The version of these terms that applies to your job is the one shown on your quote or booking confirmation. If no version is shown, it's the version published on our website on the date we issued your quote or, for work without a quote, the date you booked. If we change these terms later, the change doesn't apply to a job you've already accepted unless you agree in writing. We keep earlier versions and will send you a copy on request.",
        "These terms apply instead of any terms printed on your purchase order, subcontract form or other documents, unless we've agreed in writing to different terms for your job.",
        "If you ask us to do work on behalf of someone else (for example, as a property manager for an owner, or as a tenant), please tell us when you book. By doing so, you confirm that you have their authority, and we'll treat them as the customer. If you didn't have their authority, you're responsible for paying for the work.",
        "If more than one person accepts a quote or asks us to do the work (for example, joint owners of a home), each of you is responsible for the whole amount owing.",
        "If you accept a quote or book work as a trustee of a trust, you confirm that you have the power to do so for the trust, and you're responsible for paying both personally and as trustee.",
        "If you tell us that someone, such as your builder, architect or project manager, can act for you, they can give us instructions and approve variations for your job until you tell us in writing that they can't. If you want to limit what they can approve, please tell us the limits in writing.",
        "If you're a homeowner and we contract directly with you for residential building work, we'll give you the disclosure statement and checklist required by the Building Act 2004 before you sign if the price is likely to be $30,000 or more (including GST), or if you ask for them. For work of $30,000 or more we'll also give you a separate written contract that meets the Building (Residential Consumer Rights and Remedies) Regulations 2014. These terms apply alongside that contract, and the contract takes priority where they differ.",
      ],
    },
    {
      id: "quotes",
      heading: "Quotes, estimates and prices",
      clauses: [
        "Each quote has a quote number. It sets out the work we'll do (the scope), whether the price is a fixed price, an estimate or charge-up, any assumptions and exclusions, and the date the quote expires.",
        "Unless the quote states a different expiry date, a quote is valid for 30 days from the date it's issued.",
        "A fixed price is the price we'll charge for the work described in the quote. It changes only for variations agreed under “Changes to the work”, or as explained in this section.",
        "An estimate is our best assessment of the likely cost. It isn't a fixed price. Work priced by estimate is charged on the time and materials actually used, as set out in “Charge-up work (time and materials)”. If we expect the final cost to be more than 10% above the estimate, we'll tell you before we go further and agree with you how to proceed.",
        "Our quotes are based on the plans, specifications, selections and information that you, your builder, architect or designer give us, and on what we could reasonably see when we looked at the site. We rely on that information being accurate. If any of it changes or turns out to be different, the price may change as a variation under “Changes to the work”.",
        "If you accept a quote after its expiry date, we may update the materials prices to our current prices before we start. We'll confirm any updated price with you in writing, and you can choose not to go ahead.",
        "If work can't start within 3 months of you accepting a fixed-price quote for reasons outside our control, we may update the price of materials to reflect our suppliers' price increases since the quote. We'll show you the increase before we start, and if you're a consumer you can choose not to go ahead with the work it affects.",
        "If a product in your quote becomes unavailable, we'll tell you and suggest a comparable alternative. We'll only substitute it with your agreement, and any change in price is a variation.",
        "Unless the quote says they're included, our prices don't include building work (such as plastering, painting, carpentry or trenching), scaffolding, charges from your lines company or electricity retailer, building consent fees, or anything else not described in the quote.",
        "All prices are in New Zealand dollars. Quotes for homeowners and other consumers show the total price you'll pay, including any GST. Each quote and invoice states whether its prices include GST.",
        "If a quote or invoice contains an obvious mistake, such as a typing or adding-up error, we'll correct it and tell you. If correcting a quote increases the price, you can choose not to go ahead.",
      ],
    },
    {
      id: "charge-up",
      heading: "Charge-up work (time and materials)",
      clauses: [
        "Charge-up work is work we charge for by the time and materials used, rather than at a fixed price. It includes call-outs, fault finding, repairs, maintenance, work priced by estimate, and any work the quote says is charge-up.",
        "Labour is charged for each worker on the job, at the hourly rate for that worker shown on your quote or given to you when you booked. Rates may differ by role, and you can ask for our current rates at any time. If we think a job needs more than one worker, we'll tell you when you book or before we start.",
        "We record each worker's time for each visit in our job-management system, from when they start to when they finish, less breaks.",
        "Chargeable time includes time on site and reasonable time spent collecting materials for your job that we don't normally carry.",
        "Travel is charged as shown on your quote or booking confirmation: either as reasonable travel time at the labour rate, or as a set travel fee. We'll tell you which before we start.",
        "Each visit has a minimum charge of one hour of labour for each worker. After the first hour, time is charged in 15-minute units, rounded to the nearest 15 minutes.",
        "Materials are charged at the prices in our price list on the day they're supplied, unless your quote gives a different price. This includes sundry items used on your job, such as fixings, connectors and cable ties. We'll tell you our price for any item on request, and our charges for charge-up work will be reasonable.",
        "Finding a fault takes time, and that time is charged even if you then decide not to go ahead with the repair, or the cause turns out to be outside your electrical installation (for example, a faulty appliance or a fault on the power network).",
        "Your invoice shows the labour hours for each visit and the materials used. If you ask, we'll give you the timesheet details for your job: dates, workers, and start and finish times.",
        "If you ask us to work outside our normal hours (Monday to Friday, 7:30am to 5:30pm) and we agree, we'll tell you the rate for that work before we do it.",
      ],
    },
    {
      id: "variations",
      heading: "Changes to the work",
      clauses: [
        "A variation is any change to the work in your quote. It includes extra work you ask for, work you remove, changes to plans, selections or fittings, and extra work needed because conditions turn out to be different from what the quote assumed.",
        "We record each variation against your job and confirm it with you in writing before we do the work; email or text message is fine. The confirmation gives the price of the variation, or says that it will be charged as charge-up work. You agree to the variation by replying in writing, or by telling us to go ahead after you receive the confirmation.",
        "If you ask one of our team on site for extra or different work, that's a variation. If you ask us to do it straight away, we'll confirm it with you in writing as soon as practicable. Unless we agreed a price, it's charged as charge-up work.",
        "If we find something that must be made safe immediately to prevent danger to people or property, we'll do what's needed to make it safe and tell you as soon as we can. That work is charged as charge-up work.",
        "If we find hidden conditions that affect the work, such as asbestos, deteriorated or unsafe existing wiring, pipes or wiring hidden in walls, concrete, rock or reinforcing steel, or spaces we can't safely reach, we'll tell you before going further and agree with you how to proceed. If you decide not to go ahead with the extra work, we'll leave the installation safe, and you pay for the work done up to that point.",
        "If your builder, architect or project manager asks us to change the work and you haven't told us they can approve changes for you (see “How our agreement is made”), we'll check with you who is paying for it before we do it.",
        "If other trades move, damage or cover up our work, or remove our markings showing where fittings go, putting it right is a variation.",
        "If you ask us to decide where switches, sockets, lights or other fittings go, we'll use our judgement and experience. Moving them afterwards is a variation.",
        "A variation may change the time needed to finish the work. We'll tell you if it does.",
      ],
    },
    {
      id: "deposits",
      heading: "Deposits and materials ordered for you",
      clauses: [
        "We may ask for a deposit before we start, as stated on your quote. We usually do this for jobs over $5,000 (including GST), and when we need to order equipment specifically for your job, such as heat pumps, solar panels, batteries, EV chargers or special-order light fittings.",
        "A deposit will be no more than 50% of the quoted price, unless we agree otherwise with you in writing. It's used to buy materials for your job and to secure your booking.",
        "The deposit is due on the date shown on the deposit invoice. We may wait until it's paid before ordering materials or booking your job.",
        "Once your deposit is paid, we'll confirm a start date or start window with you.",
        "The deposit is credited against the invoices for your job. Each invoice shows how much of the deposit has been applied.",
        "If we can't start within the confirmed start window for reasons within our control and you don't want to wait, you may cancel and we'll refund your deposit in full. If you'd rather keep goods we bought for your job, we'll deliver them to you and refund the rest of the deposit.",
        "If you change your mind about fittings or equipment we've ordered for you, please tell us as soon as you can. We'll try to return them to the supplier and credit you, less any restocking fee the supplier charges us and our reasonable time to arrange the return. Special-order items the supplier won't take back are yours, and you pay for them.",
        "If you cancel a job after paying a deposit, “Cancelling or ending the work” explains what is refunded.",
      ],
    },
    {
      id: "site",
      heading: "Your site and safety",
      clauses: [
        "You must give us safe, clear access at the agreed times to the site and to the areas we need to work in, including ceiling and underfloor spaces and the switchboard.",
        "Before we start, please tell us about any hazards you know of. These include asbestos, damaged or unsafe wiring, and previous unconsented or DIY electrical work. We manage the health and safety risks of our work. If you're a business that also has duties for the site under the Health and Safety at Work Act 2015, we'll work with you to manage those risks together, and on building sites we follow the site's health and safety rules.",
        "We don't disturb or remove asbestos. If we find material we suspect contains asbestos, we'll stop work in that area until you've had it tested, or safely removed by a suitably qualified person, at your cost.",
        "Before we dig, trench or drill into the ground, please show us where underground services are, such as water, gas, drainage and irrigation pipes, and power and telecommunications cables. We'll take reasonable care and check the records available to us. We're not responsible for damage to services you didn't tell us about and that we couldn't reasonably have found, unless we were careless.",
        "If the work can only be done safely with scaffolding, we'll tell you, ideally in the quote. Unless the quote includes it, you arrange and pay for it, and it must be supplied and put up by a professional scaffolding company.",
        "Please keep pets secured and away from the work areas, open ceiling and underfloor spaces, and our vehicles while we're on site. For everyone's safety, please also keep children away from the work area.",
        "We may stop work if the site is unsafe, until the hazard is dealt with.",
        "Some work requires the power to be turned off. Where we can, we'll tell you beforehand, so you can save your work and protect computers, alarms, freezers and other sensitive equipment. Please tell us before we start if anyone on site relies on powered medical equipment. We're not responsible for lost data, lost service or spoiled goods caused by a shutdown we told you about, unless we didn't take reasonable care. If your lines company needs to disconnect or reconnect your supply, its own processes and timing apply.",
        "On building projects, the owner or head contractor normally arranges contract works insurance for the project, unless your quote says we will.",
      ],
    },
    {
      id: "timing",
      heading: "Timing and delays",
      clauses: [
        "Start and finish dates are estimates unless the quote states a fixed date. We'll keep you updated and tell you as soon as we know of any delay.",
        "We're responsible for delays within our reasonable control. We're not responsible for delays outside our reasonable control, such as weather, supply shortages, your lines company or electricity retailer, inspections, other trades, or delays caused by you. When those delays happen, we'll agree a new timetable with you.",
        "If we arrive at the agreed time and can't get in, or the site isn't ready, and you didn't give us at least 24 hours' notice, we may charge for the time reasonably lost. That charge will be no more than one hour of labour for each worker who attended.",
        "If delays caused by you, or by people you've engaged (such as your builder or other trades), mean we have to make extra visits or redo work, we may charge the reasonable extra cost as a variation. If we need to store goods for your job because of a delay you've caused, we may also charge reasonable storage costs.",
        "For new builds and staged work, please give us at least 5 working days' notice, where possible, before each stage (such as pre-wire and fit-off) is ready for us.",
      ],
    },
    {
      id: "property",
      heading: "Looking after your property",
      clauses: [
        "Please clear furniture and belongings away from the areas we'll be working in before we arrive. If we need to move anything, we'll take reasonable care.",
        "We take care to protect your property while we work, and we tidy up after ourselves and take away our own packaging and offcuts.",
        "Some work means cutting holes or channels in walls, ceilings or floors. Unless your quote says otherwise, making good afterwards (such as plastering, painting or replacing finishes) isn't included.",
        "Some work, such as trenching for a cable, can leave marks on driveways, paths, lawns or gardens. We'll tell you beforehand if that's likely, and we're not responsible for damage that's an unavoidable result of the work, unless we were careless.",
        "On building sites, general site rubbish and final cleaning are the builder's or owner's responsibility.",
        "If we damage something through our own carelessness, we'll put it right.",
      ],
    },
    {
      id: "existing-work",
      heading: "Existing wiring, safety and goods you supply",
      clauses: [
        "Our quote covers the new work it describes. We're not responsible for faults, damage or non-compliance in existing electrical work that we didn't do, unless our work, or our failure to take reasonable care, caused or contributed to it. When we connect new work to an existing installation, we check and test the connection as the law requires.",
        "If we find existing electrical work that's unsafe or doesn't comply, we'll tell you. The law may require us to make it safe or disconnect it. Any repair or upgrade not in the quote is a variation under “Changes to the work”.",
        "If we find that your switchboard, or part of your installation we've had to isolate, is unsafe, we won't turn it back on until it has been made safe. We'll explain what's needed, and what it will cost, before we do it.",
        "If your existing supply, switchboard or wiring doesn't have the capacity for the new work (for example, a heat pump, EV charger or battery), we'll tell you and quote for what's needed.",
        "If we make a temporary repair, for example to get your power back on, we'll tell you it's temporary and give you a quote or estimate for a permanent fix. A temporary repair may not stop the fault happening again.",
        "If you ask us to install something in a way we've advised against, and it's still safe and lawful, we'll ask you to confirm your choice in writing. We're not responsible for problems that result from that choice.",
        "If you supply goods for us to install, such as light fittings, appliances, heat pumps or chargers bought elsewhere, you're responsible for making sure they're complete, suitable, of good quality, and safe and compliant for use in New Zealand. You're also responsible for any warranty claim against the seller.",
        "We may decline to install goods you supply if we reasonably believe they're unsafe, non-compliant or unsuitable.",
        "We'll install goods you supply with reasonable care and skill, but we're not responsible for defects in the goods themselves. Extra time caused by faulty, incomplete or missing goods, including return visits, is charged as charge-up work.",
        "If you give us designs, plans or specifications to work from, you confirm that we can use them for your job.",
      ],
    },
    {
      id: "certificates",
      heading: "Completion and certificates",
      clauses: [
        "We test our work and carry it out to the Electricity (Safety) Regulations 2010 and the standards they cite, such as AS/NZS 3000 (the Wiring Rules).",
        "We'll issue every certificate the Electricity (Safety) Regulations 2010 require for our work, such as a Certificate of Compliance and an Electrical Safety Certificate. Where a Record of Inspection is required, we'll arrange for an electrical inspector to issue it. We give you these within the time the regulations allow, which is generally within 20 working days.",
        "We issue certificates whether or not your invoice has been paid, and we'll never hold back a certificate because of a payment dispute. Issuing a certificate doesn't affect your obligation to pay or our right to recover unpaid amounts.",
        "We send certificates electronically to the email address you gave us, and to anyone else the law requires. We'll send another copy at any time if you ask.",
        "We won't connect, turn on or certify work that's unsafe or doesn't comply with the law. This is a safety requirement, not a payment condition.",
        "Where the law requires an electrical inspector to inspect the work (for example, some solar installations and other high-risk work), the inspection fee is included in the quote or, if it isn't, charged at cost.",
        "We aim to send your certificate with or before our final invoice.",
        "When residential building work is finished, we'll give you the information the Building Act 2004 requires. This includes copies of any manufacturer guarantees or warranties, and maintenance information for the products we installed.",
      ],
    },
    {
      id: "payment",
      heading: "Paying us",
      clauses: [
        "We send invoices, payment claims, statements, reminders and notices by email (and sometimes text message) to the contact details you gave us, and they're treated as received as explained in “General”. Invoices may include a link to view and pay online. You agree that we may serve payment claims, and any other notice or document under the Construction Contracts Act 2002, on you by email to the email address you gave us. Please tell us promptly in writing if your contact details change. Until you do, we may keep using the details you gave us.",
        "We issue invoices for deposits, for progress on larger jobs, and when the work is finished. Charge-up work is invoiced when the visit or work is completed, or weekly or monthly for ongoing work.",
        "For new builds, larger renovations and commercial fit-outs, we invoice progress payments at the stages set out in the quote (for example, pre-wire, fit-off and completion). If the quote doesn't set stages, we invoice monthly for the work done that month. Progress invoices may include goods delivered to the site for your job but not yet installed.",
        "Each invoice shows its due date. Unless the invoice or your quote says otherwise, payment is due 7 days after the invoice date.",
        "If we've approved a credit account for you in writing, invoices are due on the 20th of the month after the invoice date, unless your account approval says otherwise.",
        "Please pay by bank transfer to the account shown on the invoice, or by any payment option on the online invoice, using your invoice number as the reference. Payment counts as made when cleared funds reach our account.",
        "We'll never change our bank account details by email alone. If you get a message saying our bank details have changed, call us on 027 916 2077 to check before you pay.",
        "We apply each payment to the invoice whose number you use as the payment reference or, if you've agreed a payment arrangement with us, to the amount it covers. If a payment doesn't name an invoice, we apply it to the oldest unpaid invoice first. Any interest and recovery costs are paid after the invoices they relate to.",
        "If a payment is reversed or dishonoured (for example, a card chargeback or a bank payment that's recalled), the amount is unpaid again from its original due date, unless the reversal was because of our mistake.",
        "If you think an invoice is wrong, tell us in writing (email is fine) before the due date and give your reasons. Please pay any part you don't dispute by the due date, and we'll work with you to sort out the disputed part quickly. If the invoice says it's a payment claim under the Construction Contracts Act 2002, your reply must also meet the payment schedule rules in this section. Otherwise the full amount claimed can be recovered from you.",
        "Invoices for construction work may be payment claims under the Construction Contracts Act 2002. Where they are, they'll say so and will include the prescribed information (Form 1), which explains what you need to do and what happens if you don't respond.",
        "If you disagree with a payment claim, you must give us a payment schedule by the invoice due date. The payment schedule must be in writing, identify the payment claim, and state the amount you'll pay. If that amount is less than the amount claimed, it must also say how you calculated it and why. If you don't give us a payment schedule and don't pay by the due date, the claimed amount can be recovered from you as a debt in court.",
        "If you're a builder or head contractor, our payment doesn't depend on you being paid by anyone else. We don't agree to retentions unless the quote says so. Any retention money you hold is held on trust for us as the Construction Contracts Act 2002 requires, and must be released at the time stated in the quote.",
        "If you're a business customer, you must pay our invoices in full without deduction or set-off. The only exceptions are amounts withheld under a valid payment schedule, amounts we agree to in writing, and amounts a court or adjudicator orders.",
      ],
    },
    {
      id: "cant-pay",
      heading: "If you can't pay on time",
      clauses: [
        "If you're having trouble paying, please talk to us early, ideally before the due date. Call 027 916 2077 or email enquiries@balanceelectrical.co.nz. We'd much rather work something out with you than chase an unpaid bill. If part of the reason is a concern about the work or the invoice, please tell us that too, so we can sort it out at the same time.",
        "We'll consider any reasonable proposal, such as paying in instalments over a short period. We'll confirm any arrangement we agree in writing, and we won't charge a fee for it.",
        "While you keep to an arrangement we've agreed in writing, we won't charge interest on the amount it covers or refer that amount for collection.",
        "If an agreed payment is missed and isn't paid within 5 working days after we remind you in writing, the arrangement ends. The rest of the amount it covered is then overdue and “Overdue accounts” applies, but any interest on that amount runs only from the date the arrangement ends.",
        "Contacting us doesn't change the due date unless we agree in writing. We don't offer finance or loans, but we're always happy to talk about a payment plan.",
        "If you're in financial difficulty, MoneyTalks offers free, confidential financial help on 0800 345 123 or at moneytalks.co.nz.",
      ],
    },
    {
      id: "overdue",
      heading: "Overdue accounts",
      clauses: [
        "An amount is overdue if it hasn't been paid in full by its due date.",
        "If you dispute an amount in writing, in good faith and with reasons, we won't refer it for collection or report it to a credit reporter while we work through the dispute with you. If you told us before the due date, we also won't treat it as overdue in the meantime. If it's later agreed or decided that you owe it, it's treated as overdue from its original due date. If the invoice is a payment claim under the Construction Contracts Act 2002, you still need to give us a payment schedule by the due date, as explained in “Paying us”.",
        "If an amount is overdue, we'll send you reminders by email or text message. We'll send you a written final notice before we refer the amount to a debt collection agency or lawyer, report it to a credit reporter, or start legal proceedings.",
        "If you're a business customer, we may charge interest on any overdue amount at 2.5% per month. Interest is calculated daily as simple interest (it doesn't compound), from the due date until the amount is paid in full. We don't charge interest on amounts that aren't yet due, and we don't charge interest to consumers.",
        "If you don't pay an overdue amount, you must also pay the reasonable costs we actually incur in recovering it. These include debt collection agency fees or commission (which may be a percentage of the amount collected), the reasonable fees our lawyer actually charges us, bank fees for dishonoured or reversed payments, and court, tribunal, adjudication and search fees. We don't charge a fixed late fee or administration fee. If a court or tribunal decides what costs you must pay, its decision applies.",
        "If an overdue amount is still unpaid 14 days after we send you a final notice, we may refer it to a debt collection agency or a lawyer and give them the information they need to recover it.",
        "We may also recover an overdue amount through the Disputes Tribunal, the courts, or adjudication under the Construction Contracts Act 2002.",
        "We may transfer our right to be paid an overdue amount to someone else, such as a debt collection agency. If we do, we'll tell you in writing.",
        "While an amount is overdue, we may decline new work for you, or ask for payment in advance for new work, until it's paid.",
        "If you're a business customer with a credit account and an amount is overdue, we may suspend or close the account by written notice. If we close it, all unpaid invoices on the account become due immediately.",
        "If you're a business customer and you become insolvent, go into liquidation, receivership or voluntary administration, or are adjudicated bankrupt, all amounts you owe us become due immediately.",
      ],
    },
    {
      id: "suspension",
      heading: "Suspending work for non-payment",
      clauses: [
        "For construction work, we may suspend work under section 24A of the Construction Contracts Act 2002 if: the amount claimed in our payment claim isn't paid in full by its due date and you haven't given us a payment schedule in time; the scheduled amount in your payment schedule isn't paid in full by its due date; or an amount an adjudicator has determined you must pay isn't paid in full by the date it's due. Before we suspend, we'll serve on you a written notice of our intention to suspend that states the ground, and we won't suspend until the 5 working days after the day the notice is served have passed.",
        "For other work and supply (for example, supply-only goods, design work or maintenance visits), we may stop further work or supply while an amount is overdue, after giving you at least 5 working days' written notice.",
        "Before we leave a site because of a suspension, we'll make the installation safe.",
        "A suspension doesn't affect your certificates. We'll still issue certificates for completed work as the law requires (see “Completion and certificates”).",
        "We'll resume work within a reasonable time after the overdue amount is paid. We're entitled to a reasonable extension of time for the period of the suspension, and you must pay the reasonable costs we actually incur in stopping and restarting the work.",
        "A suspension doesn't end our agreement. You remain responsible for paying for work done and materials supplied.",
      ],
    },
    {
      id: "information",
      heading: "Your information, credit checks and credit reporting",
      clauses: [
        "We collect your name, contact details, site and billing addresses, and information about your job, including site notes, photos, timesheets, certificates and payment history. We use it to quote for, plan, carry out and invoice the work; to issue the certificates and keep the records the law requires; to contact you; to manage any account; and to recover unpaid amounts. Giving us this information is voluntary, but if you don't give us what we need, we may not be able to quote, do the work, issue the certificates the law requires or offer you an account. Some of it, such as the site and owner or occupier details on electrical certificates, we must collect and keep under the Electricity (Safety) Regulations 2010. Your information is collected and held by Balance Electrical Limited, which you can contact at enquiries@balanceelectrical.co.nz or on 027 916 2077.",
        "We may also collect information about you from other people involved in your job, such as your builder, architect, property manager, landlord or tenant, or your lines company or electricity retailer. With your authorisation, we may also collect it from credit reporters. This clause is our notice to you that we may do this.",
        "We share your information only as needed for these purposes, with: our team and any subcontractors; the software providers that store our job, quoting and accounting records (including Xero); electrical inspectors, your lines company or electricity retailer, and regulators where the law or your connection requires it; your builder, property manager or other people involved in your job where needed; our accountant and lawyers, debt collection agencies, credit reporters, the courts and tribunals; and, for business customers only, the Personal Property Securities Register.",
        "We'll only obtain a credit report on you as an individual, or check with the Ministry of Justice whether you have overdue fines, with your separate authorisation, for example in a credit account application. Where the law allows, we may obtain business credit information about a company without separate authorisation.",
        "If you're an individual, we or our debt collection agency may give your details and the overdue amount to credit reporters (such as Centrix or Equifax) when all of these apply: the amount is $125 or more; it's at least 30 days overdue; we've told you it's overdue and asked you to pay; we've taken other steps to recover it; and we're not legally prevented from suing for it. A credit reporter may record a payment default on your credit file for up to five years, which may affect your ability to get credit.",
        "We won't report as a default, or refer for collection, any amount you've disputed in writing in good faith while we're working through the dispute with you.",
        "We store your information securely. We keep it for as long as we need it for these purposes and for as long as the law requires, including for electrical records.",
        "We take photos of our work for job records, certification and quality checks, and we may use photos of finished work in our portfolio, on our website and social media, and in award entries. We never show your address, people or anything else that identifies you. If you'd rather we didn't use photos of your home or premises, tell us at any time (for example, when you accept your quote, or by emailing enquiries@balanceelectrical.co.nz) and we won't use them in new marketing.",
        "You can ask to see or correct the personal information we hold about you by emailing enquiries@balanceelectrical.co.nz. We'll respond as the Privacy Act 2020 requires.",
      ],
    },
    {
      id: "ownership",
      heading: "Ownership of goods and security",
      clauses: [
        "If you're a consumer, goods we hold for your job remain ours until they're delivered to you, installed or paid for. After that, they belong to you. We don't take a security interest over your goods or property, and we'll never enter your home to remove goods we've installed.",
        "Goods we supply and install are our responsibility until they're installed. If we supply goods without installing them, they're your responsibility once they're delivered to the address you gave us, even if no one is there to receive them.",
        "If you're a business customer, ownership of goods we supply to you stays with us until you've paid all amounts you owe us. Until then, you hold the goods for us and must keep them safe, insured and identifiable as ours.",
        "If you're a business customer and you've signed, or accepted by email, text message or online acceptance, a quote, credit account application or other document that refers to these terms, these terms are a security agreement under the Personal Property Securities Act 1999. You grant us a security interest in all goods we supply to you, and in their proceeds, as security for all amounts you owe us. We may register a financing statement on the Personal Property Securities Register, and you'll give us any information we reasonably need to do so.",
        "If you're a business customer, then to the extent the Personal Property Securities Act 1999 allows: you waive your right to receive a verification statement; you agree that sections 114(1)(a), 133 and 134 of that Act don't apply; and you waive your rights under sections 116, 120(2), 121, 125, 126, 127, 129, 131 and 132 of that Act. In plain terms, this means we don't have to give you some of the notices the Act would otherwise require when we register or enforce our security.",
        "If you're a business customer and you sell or otherwise deal with goods we supplied before you've paid for them, you hold the proceeds on trust for us and must pay them to us on request, up to the amount you owe us.",
        "If you're a business customer, we won't remove goods that have been installed and have become part of a building. Goods that haven't been installed and can be removed without damage may be recovered on reasonable written notice, during business hours, with your consent or a court order. Any amount we receive for recovered goods is credited to your account.",
        "If your business wants a credit account, we may ask for a written credit account application. If you're a company, we may also ask for a personal guarantee signed by your directors.",
        "If you're a business customer with a credit account, you charge your interest in any land you own, now or later, as security for amounts you owe us that are overdue, and you agree that we may register a caveat to protect that charge. We'll give you at least 10 working days' written notice before we register a caveat, and we'll remove it promptly once you've paid what you owe.",
        "If you're a business customer, please tell us in writing at least 14 days before you change your name, ownership, legal structure or address.",
        "If you're a business customer and we supply goods without installing them, please check them when they're delivered and tell us within 7 days about any damage, shortage or wrong item.",
      ],
    },
    {
      id: "cancellation",
      heading: "Cancelling or ending the work",
      clauses: [
        "You may cancel a job before work starts by telling us in writing. We'll refund any deposit, less the reasonable costs we've actually incurred or committed to, such as special-order or non-returnable goods, supplier restocking fees, and design or site time. We'll show you how we worked this out.",
        "If we keep part of a deposit to pay for goods bought for your job, those goods are yours, and we'll deliver them to you if you ask.",
        "You may end the work after it has started by telling us in writing. You then pay for the work done up to that point (at the quoted price for completed stages, or as charge-up work), for materials supplied or ordered that can't be returned, and the reasonable cost of leaving the site safe. We'll refund any money you've paid for work not done.",
        "If we need to cancel a job for a reason you didn't cause, we'll refund all money you've paid for work not done and for goods you don't keep.",
        "Either of us may end our agreement by written notice if the other seriously breaches it and doesn't fix the breach within 10 working days after receiving written notice describing it. Examples of a serious breach are not paying an overdue amount, or failing to carry out the work properly. This doesn't limit any right you have as a consumer to cancel straight away under the Consumer Guarantees Act 1993 or the Contract and Commercial Law Act 2017.",
        "If you're a business customer, either of us may end our agreement immediately by written notice if the other becomes insolvent or goes into liquidation, receivership or voluntary administration.",
        "Ending our agreement doesn't affect amounts already owing, certificates for completed work, or any other rights either of us already has.",
        "These terms don't limit any right you have by law to cancel, such as the cooling-off period for some uninvited direct sales.",
      ],
    },
    {
      id: "guarantees",
      heading: "Guarantees and our responsibility",
      clauses: [
        "If you're a consumer, the Consumer Guarantees Act 1993 gives you guarantees that can't be excluded. These include that our services will be carried out with reasonable care and skill; that they'll be fit for any particular purpose you made known to us; that they'll be completed within a reasonable time and at a reasonable price, where no time or price was agreed; and that goods we supply will be of acceptable quality.",
        "For residential building work, the warranties implied by the Building Act 2004 also apply and can't be excluded. If you tell us in writing about a defect within 12 months after the work is completed, we'll fix it within a reasonable time, as the Act requires. The implied warranties continue after those 12 months, and claims for breach of them can generally be brought for up to 10 years.",
        "We pass on the benefit of any manufacturer's warranty for products we supply, such as heat pumps, inverters, batteries, EV chargers and light fittings, and we'll help you make a claim under it. If you're a consumer, you can also come to us directly under the Consumer Guarantees Act about a fault in goods we supplied; you don't have to go to the manufacturer first. Some manufacturer warranties require the product to be registered or serviced, and we'll pass on to you any information we receive about this.",
        "If you think there's a problem with our work or with goods we supplied, please tell us as soon as you can by calling 027 916 2077 or emailing enquiries@balanceelectrical.co.nz, with your job number and, if possible, photos. We'll arrange a time to inspect it, and if the problem is covered by our responsibilities under these terms or the law, we'll fix it at no charge. Please give us a reasonable opportunity to do this. This doesn't limit your rights as a consumer, including your right to have the problem fixed by someone else and recover the reasonable cost from us if we refuse or fail to fix it within a reasonable time.",
        "If we inspect a reported problem and find it wasn't caused by our work or by goods we supplied (for example, a faulty appliance, a power network fault or work done by others), we may charge the visit as charge-up work. If that seems likely from what you tell us, we'll say so before we come out.",
        "We're not responsible for loss or damage caused by existing electrical work or goods that we didn't supply or install; by defects in goods you supplied; by misuse, accidents, lack of maintenance, or work done by others after us; or by power network faults, outages or surges outside our control. This doesn't limit your rights as a consumer.",
        "If you're a business customer acquiring our goods or services in trade, you and we agree that, to the extent permitted by section 43 of the Consumer Guarantees Act 1993 and section 5D of the Fair Trading Act 1986, the Consumer Guarantees Act and sections 9, 12A, 13 and 14(1) of the Fair Trading Act don't apply, and that it's fair and reasonable for this to bind us both. In plain terms, if you're a business customer, you can't make claims against us under the Consumer Guarantees Act or those sections of the Fair Trading Act; your rights come from these terms and the general law.",
        "If you're a business customer, our total liability to you for any claim about a job is limited to the price of that job, and we're not liable for indirect or consequential loss, such as loss of profit, revenue or business interruption. This limit doesn't apply to liability that can't be limited by law, or to loss caused by our fraud or wilful misconduct.",
        "If you're a business customer, we don't give any guarantee or warranty beyond those described in this section unless it's stated in writing in your quote. If you're a consumer, please ask us to put in writing anything we tell you about the work that matters to you, such as how a product will perform. This doesn't limit your rights as a consumer.",
      ],
    },
    {
      id: "disputes",
      heading: "Disputes and complaints",
      clauses: [
        "If you have a concern or complaint, please contact us first on 027 916 2077 or at enquiries@balanceelectrical.co.nz. We aim to respond within 5 working days.",
        "We'll try to resolve any dispute with you promptly and in good faith. Either of us may suggest mediation. If we both agree to it, we'll share the mediator's fee equally unless we agree otherwise.",
        "Nothing in these terms limits your right, or ours, to take a claim to the Disputes Tribunal (if it's within the Tribunal's limit), to the courts, or to adjudication under the Construction Contracts Act 2002.",
        "If you have a concern about the conduct or competence of a registered electrical worker, you can also complain to the Electrical Workers Registration Board.",
        "While a dispute is being resolved, please pay any amount that isn't in dispute by its due date.",
      ],
    },
    {
      id: "general",
      heading: "General",
      clauses: [
        "In these terms, “in writing” includes email, text message, online acceptance and electronic signatures.",
        "We send notices to the email address or mobile number you gave us, and you can send notices to us at enquiries@balanceelectrical.co.nz. A notice sent by email or text message by either of us is treated as received when it's sent, unless the sender gets a message that it couldn't be delivered.",
        "We may update these terms from time to time. An updated version applies only to quotes we issue and work we book after it's published on our website, as explained in “How our agreement is made”.",
        "We may use suitably qualified and, where required, licensed subcontractors for parts of the work. We remain responsible to you for their work. Please give any instructions about the work to us rather than directly to our subcontractors.",
        "We own the copyright in the lighting designs, plans, drawings and specifications we prepare. While we're doing the work, you and the people working on your project may use them for that project. Once you've paid for the design work (or, if design isn't charged separately, for the work it relates to), you may keep using them for that property, including for later maintenance and alterations. If you paid us a separate design fee, you may also give them to another contractor to price or install that project. Otherwise, you may not use them for another project, or give them to another contractor, without our written consent.",
        "We hold public liability insurance of at least $5 million.",
        "You may not transfer your rights or obligations under our agreement to someone else without our written consent.",
        "Neither of us is responsible for failing to meet our obligations (other than paying money) because of events outside our reasonable control, such as natural disasters, extreme weather, pandemics, power network failures or industrial action.",
        "If we don't enforce a right straight away, we can still enforce it later.",
        "If any part of these terms is found to be unenforceable, the rest of the terms still apply.",
        "These terms are governed by New Zealand law, and the New Zealand courts and tribunals have jurisdiction.",
      ],
    },
  ],
};

/** The printable copy of this version, made by scripts/terms-pdf.tsx (in public/). */
export const TERMS_PDF = `/balance-electrical-terms-of-trade-v${TERMS.version}.pdf`;
