/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AreasOfExpertiseRouteImport } from './routes/areas-of-expertise'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EnquiriesRouteImport } from './routes/enquiries'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsOfTradeRouteImport } from './routes/terms-of-trade'
import { Route as ApiReviewsStatusRouteImport } from './routes/api.reviews-status'
import { Route as AreasIndexRouteImport } from './routes/areas.index'
import { Route as AreasSlugRouteImport } from './routes/areas.$slug'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio_.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasOfExpertiseRoute = AreasOfExpertiseRouteImport.update({
  id: '/areas-of-expertise',
  path: '/areas-of-expertise',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiriesRoute = EnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfTradeRoute = TermsOfTradeRouteImport.update({
  id: '/terms-of-trade',
  path: '/terms-of-trade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewsStatusRoute = ApiReviewsStatusRouteImport.update({
  id: '/api/reviews-status',
  path: '/api/reviews-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasIndexRoute = AreasIndexRouteImport.update({
  id: '/areas/',
  path: '/areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasSlugRoute = AreasSlugRouteImport.update({
  id: '/areas/$slug',
  path: '/areas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio_/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/areas-of-expertise': typeof AreasOfExpertiseRoute
  '/contact': typeof ContactRoute
  '/enquiries': typeof EnquiriesRoute
  '/gallery': typeof GalleryRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/portfolio': typeof PortfolioRoute
  '/projects': typeof ProjectsRoute
  '/review': typeof ReviewRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-trade': typeof TermsOfTradeRoute
  '/api/reviews-status': typeof ApiReviewsStatusRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/areas/': typeof AreasIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/areas-of-expertise': typeof AreasOfExpertiseRoute
  '/contact': typeof ContactRoute
  '/enquiries': typeof EnquiriesRoute
  '/gallery': typeof GalleryRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/portfolio': typeof PortfolioRoute
  '/projects': typeof ProjectsRoute
  '/review': typeof ReviewRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-trade': typeof TermsOfTradeRoute
  '/api/reviews-status': typeof ApiReviewsStatusRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/areas': typeof AreasIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/areas-of-expertise': typeof AreasOfExpertiseRoute
  '/contact': typeof ContactRoute
  '/enquiries': typeof EnquiriesRoute
  '/gallery': typeof GalleryRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/portfolio': typeof PortfolioRoute
  '/projects': typeof ProjectsRoute
  '/review': typeof ReviewRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-trade': typeof TermsOfTradeRoute
  '/api/reviews-status': typeof ApiReviewsStatusRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/portfolio_/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/areas/': typeof AreasIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/areas-of-expertise'
    | '/contact'
    | '/enquiries'
    | '/gallery'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/portfolio'
    | '/projects'
    | '/review'
    | '/sitemap.xml'
    | '/terms-of-trade'
    | '/api/reviews-status'
    | '/areas/$slug'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/areas/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/areas-of-expertise'
    | '/contact'
    | '/enquiries'
    | '/gallery'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/portfolio'
    | '/projects'
    | '/review'
    | '/sitemap.xml'
    | '/terms-of-trade'
    | '/api/reviews-status'
    | '/areas/$slug'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/areas'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/areas-of-expertise'
    | '/contact'
    | '/enquiries'
    | '/gallery'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/portfolio'
    | '/projects'
    | '/review'
    | '/sitemap.xml'
    | '/terms-of-trade'
    | '/api/reviews-status'
    | '/areas/$slug'
    | '/portfolio_/$slug'
    | '/services/$slug'
    | '/areas/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AreasOfExpertiseRoute: typeof AreasOfExpertiseRoute
  ContactRoute: typeof ContactRoute
  EnquiriesRoute: typeof EnquiriesRoute
  GalleryRoute: typeof GalleryRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PortfolioRoute: typeof PortfolioRoute
  ProjectsRoute: typeof ProjectsRoute
  ReviewRoute: typeof ReviewRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfTradeRoute: typeof TermsOfTradeRoute
  ApiReviewsStatusRoute: typeof ApiReviewsStatusRoute
  AreasSlugRoute: typeof AreasSlugRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  AreasIndexRoute: typeof AreasIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-of-expertise': {
      id: '/areas-of-expertise'
      path: '/areas-of-expertise'
      fullPath: '/areas-of-expertise'
      preLoaderRoute: typeof AreasOfExpertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiries': {
      id: '/enquiries'
      path: '/enquiries'
      fullPath: '/enquiries'
      preLoaderRoute: typeof EnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-trade': {
      id: '/terms-of-trade'
      path: '/terms-of-trade'
      fullPath: '/terms-of-trade'
      preLoaderRoute: typeof TermsOfTradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviews-status': {
      id: '/api/reviews-status'
      path: '/api/reviews-status'
      fullPath: '/api/reviews-status'
      preLoaderRoute: typeof ApiReviewsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/': {
      id: '/areas/'
      path: '/areas'
      fullPath: '/areas/'
      preLoaderRoute: typeof AreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$slug': {
      id: '/areas/$slug'
      path: '/areas/$slug'
      fullPath: '/areas/$slug'
      preLoaderRoute: typeof AreasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio_/$slug': {
      id: '/portfolio_/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AreasOfExpertiseRoute: AreasOfExpertiseRoute,
  ContactRoute: ContactRoute,
  EnquiriesRoute: EnquiriesRoute,
  GalleryRoute: GalleryRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PortfolioRoute: PortfolioRoute,
  ProjectsRoute: ProjectsRoute,
  ReviewRoute: ReviewRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfTradeRoute: TermsOfTradeRoute,
  ApiReviewsStatusRoute: ApiReviewsStatusRoute,
  AreasSlugRoute: AreasSlugRoute,
  PortfolioSlugRoute: PortfolioSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  AreasIndexRoute: AreasIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
